### ISSUE TITLE
Alignment of the logo isn't correct

### ISSUE THREAD

**Issue by Khaan25** [twentyhq/twenty#7833] opened 2024-10-18 18:20 UTC
## Bug Description

![image](https://github.com/user-attachments/assets/e099e69e-7a64-483b-8175-72a85531fca8)

## Expected behavior

It should be aligned with the rest of the menu items

**Comment by harshrajeevsingh** [comment] 2024-10-18 19:11
@Khaan25 I can't reproduce it. What browser are you using? Although I checked it on both Chrome & Firefox.

**Comment by dishafaujdar** [comment] 2024-10-19 04:40
@Khaan25 can i work on it ?

**Comment by Khaan25** [comment] 2024-10-19 04:47
Can you reproduce it?

**Comment by FelixMalfait** [comment] 2024-10-19 07:19
I also can't reproduce it (Chrome)

**Comment by Bonapara** [comment] 2024-10-19 14:39
Cannot reproduce on main

**Comment by Bonapara** [comment] 2024-10-19 14:39
I'm closing this, but please comment, and I'll reopen it if you experience the issue too!

**Closed by Bonapara** 2024-10-19 14:39 UTC
Labels: type: bug

**Comment by Khaan25** [comment] 2024-10-22 16:39
@Bonapara I can still see this on production
![image](https://github.com/user-attachments/assets/9469d006-d8d2-4ec8-b700-4e2469839b62)
