### ISSUE TITLE
Update webhook is sent after clicking on API key's name

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7844] opened 2024-10-19 10:00 UTC
**Scenario:**
1. Log in
2. Go to Settings
3. Toggle "Advanced" on
4. Go to API & Webhooks
5. Create new webhook
6. Create new API key or use existing one
7. Check details of API key
8. Click on API key's name input, then outside of it

**Actual:** After creating new API key, 2 webhooks are sent (create and update), after clicking on API key's name input, then outside of it, webhook update is sent despite no change in API key's name

**Expected:** After creating new API key, 1 webhook (create) must be sent, after clicking on API key's name input, then outside of it, webhook must be sent only if name has changed

**Comment by Bonapara** [comment] 2024-10-19 14:44
Cannot reproduce on main 🤔 

https://github.com/user-attachments/assets/d5cb8f51-4cb9-4299-8e5b-6446e40a1d72

**Comment by Bonapara** [comment] 2024-10-19 14:46
Hi @ehconitin! Can you have a look next week?

**Comment by ehconitin** [comment] 2024-10-19 17:51
@Bonapara This happens because we don't have manual save/cancel buttons to update the API key name. It's done with a debounced call on input change, so every initial render triggers an update. Is there a reason we didn't include a manual save for the API page? I didn't see it in the Figma designs either.

**Comment by Bonapara** [comment] 2024-10-21 08:18
Thanks for your investigation, @ehconitin! Autosave is always better for UX when possible. I think we can keep it as it is today, so I'll close this issue for now.

**Closed by Bonapara** 2024-10-21 08:18 UTC
Labels: type: bug
