### ISSUE TITLE
Error 'missing FROM-clause entry for table "workspacemember"' doesn't allow deleting or creating new members

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7449] opened 2024-10-05 08:56 UTC
**Scenario:**
1. Log in
2. Go to Settings > Members
3. Delete any member created by system

**Actual:** Member is not deleted and error is thrown
[Screencast From 2024-10-05 10-54-33.webm](https://github.com/user-attachments/assets/deb2da78-f362-4f44-b06e-d271382327db)

**Expected:** Member must be deleted

```
query failed: UPDATE "workspace_1wgvd1injqtife6y4rvfbu3h5"."workspaceMember" SET "deletedAt" = $1, "updatedAt" = CURRENT_TIMESTAMP WHERE workspaceMember.id = $2 RETURNING * -- PARAMETERS: ["2024-10-05T08:54:36.044Z","20202020-77d5-4cb6-b60a-f4a835a85d61"]
error: error: missing FROM-clause entry for table "workspacemember"
Exception Captured
  {
    operation: { name: 'DeleteOneWorkspaceMember', type: 'mutation' },
    document: 'mutation DeleteOneWorkspaceMember($idToDelete: ID!) {\n' +
      '  deleteWorkspaceMember(id: $idToDelete) {\n' +
      '    __typename\n' +
      '    id\n' +
      '    deletedAt\n' +
      '  }\n' +
      '}',
    user: User {
      id: '20202020-9e3b-46d4-a556-88b9ddc2b034',
      firstName: 'Tim',
      lastName: 'Apple',
      email: 'tim@apple.dev',
      defaultAvatarUrl: null,
      emailVerified: false,
      disabled: false,
      passwordHash: '$2b$10$66d.6DuQExxnrfI9rMqOg.U1XIYpagr6Lv05uoWLYbYmtK0HDIvS6',
      canImpersonate: false,
      createdAt: 2024-10-03T23:11:02.911Z,
      updatedAt: 2024-10-04T18:26:59.846Z,
      deletedAt: null,
      defaultWorkspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419'
    }
  }
  [
    QueryFailedError: missing FROM-clause entry for table "workspacemember"
        at PostgresQueryRunner.query (/home/mk/Desktop/projects/twenty/src/driver/postgres/PostgresQueryRunner.ts:331:19)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at UpdateQueryBuilder.execute (/home/mk/Desktop/projects/twenty/src/query-builder/UpdateQueryBuilder.ts:145:33)
        at GraphqlQueryUpdateOneResolverService.resolve (/home/mk/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/resolvers/graphql-query-update-one-resolver.service.ts:68:20)
        at GraphqlQueryRunnerService.executeQuery (/home/mk/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts:334:21)
        at GraphqlQueryRunnerService.deleteOne (/home/mk/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/graphql-query-runner/graphql-query-runner.service.ts:221:20)
        at GraphqlQueryRunnerService.descriptor.value (/home/mk/Desktop/projects/twenty/packages/twenty-server/src/engine/decorators/observability/log-execution-time.decorator.ts:20:22)
        at Object.deleteWorkspaceMember (/home/mk/Desktop/projects/twenty/packages/twenty-server/src/engine/api/graphql/workspace-resolver-builder/factories/delete-one-resolver.factory.ts:53:18)
        at field.resolve (/home/mk/Desktop/projects/twenty/node_modules/@envelop/on-resolve/cjs/index.js:36:42)
        at /home/mk/Desktop/projects/twenty/node_modules/@envelop/core/cjs/orchestrator.js:383:27 {
      path: undefined,
      locations: undefined,
      extensions: {
        code: 'INTERNAL_SERVER_ERROR',
        response: 'missing FROM-clause entry for table "workspacemember"'
      }
    }
  ]
```

**Comment by BOHEUS** [comment] 2024-10-05 09:02
**Scenario:**
1. Log in
2. Go to Settings > Members
3. Copy invite link
4. Logout
5. Paste copied link and create new account

**Actual:** System won't allow finishing creating new account
[Uploading Screencast From 2024-10-05 11-01-22.webm…]()

**Expected:** User can create new account

**Comment by BOHEUS** [comment] 2024-10-05 10:19
This problem also appears when user tries to change anything in Settings > Experience, Settings > Accounts > Emails, Settings > Accounts > Calendar, creates new API key or webhook in Settings > API & Webhooks

**Comment by charlesBochet** [comment] 2024-10-05 10:31
@BOHEUS is that on main our on prod (0.30.2) ?

**Comment by BOHEUS** [comment] 2024-10-05 10:36
@charlesBochet I've found it locally after pulling newest changes, checked demo as I don't have paid version and is seems like this bug isn't there (there's different bug with inviting new people, but that's topic for another issue)

**Comment by BOHEUS** [comment] 2024-10-05 11:41
Database logs
```
twenty_postgres  | 2024-10-05 11:38:20.005 GMT [1012] ERROR:  missing FROM-clause entry for table "workspacemember" at character 126
twenty_postgres  | 2024-10-05 11:38:20.005 GMT [1012] STATEMENT:  UPDATE "workspace_1wgvd1injqtife6y4rvfbu3h5"."workspaceMember" SET "colorScheme" = $1, "updatedAt" = CURRENT_TIMESTAMP WHERE workspaceMember.id = $2 RETURNING *
```

**Comment by charlesBochet** [comment] 2024-10-05 14:27
Ok @Weiko will likely take a close look on Monday, thanks for spotting it!

**Comment by Weiko** [comment] 2024-10-07 13:16
This one should have been fixed already, I can't reproduce on main. Can you try again? @BOHEUS

**Comment by BOHEUS** [comment] 2024-10-07 16:29
Sure, I'll fetch newest changes and check it ASAP

**Comment by BOHEUS** [comment] 2024-10-07 16:57
I'm closing this as I can't also reproduce it after pulling newest changes from main

**Comment by BOHEUS** [comment] 2024-11-24 19:36
I'm reopening this as I'm able to reproduce it on main and also, ticket was created by one of users https://discord.com/channels/1130383047699738754/1310321595457470504

CC: @Weiko

**Comment by BOHEUS** [comment] 2024-11-24 19:42
Btw, it's also reproducible on demo, what a sneaky one
https://github.com/user-attachments/assets/a18b1c53-871d-4c1b-b9aa-a72a2db34974

**Comment by FelixMalfait** [comment] 2024-11-29 16:34
@Weiko this is the casing issue your told me about recently (missing `"` in the from clause around workspacemember), has this been fixed? I don't remember

**Comment by Weiko** [comment] 2024-11-29 18:16
@FelixMalfait yes, should have been fixed in the .33.4!

**Closed by Weiko** 2024-11-29 18:16 UTC

**Comment by FelixMalfait** [comment] 2024-11-29 18:45
Thank you @weiko
