### ISSUE TITLE
BUG - Double event listener cause strange freeze on inputs

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#631] opened 2023-07-12 23:08 UTC
If we have two onClick on a component, for example on a checkbox and on its container, we can obtain race condition where the state is stucked and it then requires to move the mouse to complete the change.

We have to be sure that only one listener handles our event at the same time.

This is also related to issue with isSomeInputInEditMode, that may be removed because it was a poor attempt to solve this problem.

We should have a clear pattern for checking that we have only one event listener handling an event anywhere in the app.

**Comment by charlesBochet** [comment] 2024-01-13 11:41
I cannot reproduce anymore, closing this issue

**Closed by charlesBochet** 2024-01-13 11:41 UTC
Labels: scope: front, blocked: tech spec needed, type: chore, size: days
