### ISSUE TITLE
Timeline tasks are only clickable after accessing Tasks tabs

### ISSUE THREAD

**Issue by anamarn** [twentyhq/twenty#6952] opened 2024-09-09 13:27 UTC
## Bug Description

Timeline tasks are only clickable after you access the Tasks tab. 

**Example:** 

https://github.com/user-attachments/assets/9af2a2a8-32ef-4d60-bb50-be90131c9186

## Expected behavior

When a task name appears the timeline, I can click on it and see the task directly without passing by the tasks Tab.
<img width="1900" alt="Screenshot 2024-09-09 at 15 23 05" src="https://github.com/user-attachments/assets/b33f196a-4306-4d3f-a53a-18a7e1d8eb38">
<img width="1913" alt="Screenshot 2024-09-09 at 15 24 38" src="https://github.com/user-attachments/assets/fba3a772-f2d4-4097-8e59-a0907a3f43a9">

**Comment by harshit078** [comment] 2024-09-09 14:03
@anamarn, One more issue which can be seen is that if no space is given when writing task and clicked outside, the task doesn't seem to update and requires one more visit

https://github.com/user-attachments/assets/0cce6b92-498f-4055-b906-125d2ec97b27

**Comment by ehconitin** [comment] 2024-10-15 13:56
@Bonapara I couldnt reproduce!
Could you?

**Comment by Bonapara** [comment] 2024-10-15 14:56
Can't reproduce the issue either, so closing it. Please reopen if you still encounter the bug, @anamarn!

**Closed** 2024-10-15 14:56 UTC
Labels: type: bug, scope: front, size: short, prio: high
