### ISSUE TITLE
Tasks editor should be scrollable to show complete content

### ISSUE THREAD

**Issue by i-am-chitti** [twentyhq/twenty#3120] opened 2023-12-22 00:32 UTC
## Bug Description

While typing in tasks editor, if content becomes larger than the available space, it doesn't scroll further. Due to which, the some parts at end of the editor is not visible until user deletes some content above. Also, while user presses "Enter" key, it doesn't automatically scroll to next part due to which the current cursor position is not into view.

https://github.com/twentyhq/twenty/assets/60139930/cfb71e3a-6cbb-4233-b506-b512fca5ea8e

## Expected behavior

- It should be scrollable up and down showing complete content in the editor.
- On pressing "Enter", it should scroll to bring the current cursor into view.

**Comment by FelixMalfait** [comment] 2023-12-25 17:30
Good catch thanks!

**Comment by FelixMalfait** [comment] 2023-12-25 17:37
I think the issue is with the comment bar. For me it does scroll automatically when I type but not enough, it's still hidden by the command bar's height.

@Bonapara I feel like we should review the comment feature, maybe disable it in the meantime? One thing that would work best would be to have a line-by-line comments? I think that's doable and we could reuse most of the current work (maybe half a day of backend work + two days of frontend to adapt properlu)

**Comment by Bonapara** [comment] 2024-01-02 11:06
We could consider a temporary `margin-bottom` to prevent content from hiding under the comments assuming it's indeed the problem.

@FelixMalfait, could you specify your thoughts on line-by-line comments? Do you mean a Notion-like feature to comment on individual sentences or words? I plan to work on improving the comment section soon.

**Comment by FelixMalfait** [comment] 2024-01-02 11:08
> Do you mean a Notion-like feature to comment on individual sentences or words? 
@Bonapara yes that's what I meant. Cool if you had plans to improve it! I'll let you give the final word on what needs to be done on this issue / add relevant tags if good first issue.

**Comment by Bonapara** [comment] 2024-01-02 11:18
Felix is correct. The problem is that the comment section is covering the bottom of the note. To fix this, we need to add a 64px margin-bottom to the content section. This will also enhance the visibility between the content and the comments:

![CleanShot 2024-01-02 at 12 15 10@2x](https://github.com/twentyhq/twenty/assets/19412894/32fd4f12-1c50-4ef9-9a07-b7f26cffe8da)

**Comment by FelixMalfait** [comment] 2024-02-21 14:57
This now seems to be fixed on the main branch!

**Closed by FelixMalfait** 2024-02-21 14:57 UTC
Labels: type: bug
