### ISSUE TITLE
Revert change on stroke of icons in 'Options', 'Sort' and Filter' menu

### ISSUE THREAD

**Issue by jenalla** [twentyhq/twenty#1511] opened 2023-09-07 23:08 UTC
### scope: 
All the menus in:
- 'People' page
- 'Companies' page
- 'Opportunities' page

# Styling Adjustments:

Currently, all icons within DropdownMenuItem have a stroke size set to 'md', adjust the stroke size of those icons to 'sm'. 

![Image](https://user-images.githubusercontent.com/102394218/266461165-cd07fb1f-353c-4db3-8751-45a124d93d82.png)

**Comment by charlesBochet** [comment] 2023-09-18 05:58
@jenalla I can't reproduce this one on app main:
<img width="768" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/6895d72f-91a2-4583-9618-44cac1806218">

Closing the ticket but let's re-open it if I missed something!

**Closed by charlesBochet** 2023-09-18 05:58 UTC
Labels: scope: front, blocked: false, size: minutes, type: design improvement
