### ISSUE TITLE
Using up+right keyboard in the table makes the soft focus go one cell too far.

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#462] opened 2023-06-28 10:59 UTC
To reproduce : go to an entity table cell and and do up and down rapidly, it should go one cell too far.

**Comment by FelixMalfait** [comment] 2023-07-21 11:54
I was able to reproduce by pressing ⬆️ and ➡️ at the same time on my keyboard

**Comment by brendanlaschke** [comment] 2023-07-27 12:48
The cause seems to be in the react-hotkeys-hook library as wrong events are sent while the keyup event not has been registered: 
https://github.com/JohannesKlauss/react-hotkeys-hook/issues/1013

**Comment by brendanlaschke** [comment] 2023-11-16 09:30
Update: the fix has been merged we are waiting for a new release of https://github.com/JohannesKlauss/react-hotkeys-hook

**Closed** 2024-01-11 07:47 UTC
Labels: type: bug, scope: front, blocked: conflict/dependency, size: hours
