### ISSUE TITLE
Selecting and releasing the mouse outside of an edit mode cell closes it

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1734] opened 2023-09-26 09:13 UTC
## Bug Description

When we open a cell with an input (for example email) and we select the text, and the mouse up event ends up outside of the input, the cell is closed.

https://github.com/twentyhq/twenty/assets/26528466/5a58f7d1-501e-436a-94a9-6b95c53ed94d

## Expected behavior

We want this to be avoided for those specific inputs. We shouldn't modify the useListenClickoutside, but instead find a way to have the right events listened.

Maybe use onMouseUp or ouMouseDown on GenericCellEditMode ? 

The fix shouldn't break existing behaviors, ensure for example that a click outside of a cell doesn't open another cell directly, the first click outside should only exit the edit mode of the current cell.

**Comment by abhithory** [comment] 2023-09-27 18:32
Thanks for the  video, I am working on this and will let you when it got fixed

**Comment by abhithory** [comment] 2023-10-09 07:47
Hi @lucasbordeau , I have fixed this issue and created PR. Please check and let me know if there is any other improvment/.

PR: #1933

**Comment by lucasbordeau** [comment] 2023-10-09 13:40
I'll let @charlesBochet review this

**Comment by tomalexing** [comment] 2023-10-15 13:29
But by editing useListenClickoutside we could fix this behavior on every component, because this bug on every dropdown.

**Comment by abhithory** [comment] 2023-10-15 14:09
Dear @tomalexing, they have mentioned in the issue that `We shouldn't modify the useListenClickoutside`

**Comment by tomalexing** [comment] 2023-10-15 14:50
Yes , If we are talking about just to fix the InputText Component. I am talking about fix this bug for all of them.

**Comment by abhithory** [comment] 2023-10-15 17:53
this is not a bug, it is feature for some components.

**Comment by lucasbordeau** [comment] 2023-10-30 13:06
@tomalexing @abhithory actually, we could think of a new property `skipIfMouseDownInsideButMouseUpOutside` on `useListenClickOutside`

@abhithory We don't allow useRef as state management in our codebase.

**Comment by charlesBochet** [comment] 2023-11-28 23:50
This has been solved, closing the issue!

**Closed by charlesBochet** 2023-11-28 23:50 UTC
Labels: type: bug, scope: front, ready
