### ISSUE TITLE
Customization of Select Values and Visibility in Kanban Boards

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4356] opened 2024-03-07 11:10 UTC
We aim to enable users to customize Select values on a kanban and toggle the Display/Hide Select option easily. 

### Desired functionality

The intended behavior should function across all types of kanban boards.

1. Add a new `Stages` item in the `Options` menu.
2. Selecting `Hidden Stages` should reveal hidden Select values on the view.
3. Choosing `Edit field values` should direct users to the Field settings page.

https://app.twenty.com/settings/objects/opportunities/stage 

![737383afe49c5fc821a275fc4e7bfe3c7a7d7c4f105542918f521f02c207124a](https://github.com/user-attachments/assets/d735714c-8550-4e4a-9d7e-284ad3ccfaf3)

### Select hover

We should use the `Button` menu item component and display a `eye-off` icon to hide a Select value from a kanban and a `eye` icon to display a hidden Select.

![CleanShot 2024-03-07 at 12 04 54](https://github.com/twentyhq/twenty/assets/19412894/630c8eb4-028f-4e7e-b9a5-246914ba2308)

### Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24955-194238&node-type=FRAME&t=pnO27TUFBJdQcKXz-11

# Related issue: https://github.com/twentyhq/twenty/issues/5987

**Comment by Bonapara** [comment] 2024-03-07 11:11
Related to #2483

**Comment by FelixMalfait** [comment] 2024-04-22 07:49
I think this is a duplicate of https://github.com/twentyhq/twenty/issues/4244 which has an ongoing PR?
Closing but please re-open if not!

**Comment by Bonapara** [comment] 2024-04-22 08:06
This issue concerns the Kanban `Options menu` and not the Kanban `Column Header menu`. To me, they are not related @FelixMalfait!

![CleanShot 2024-04-22 at 10 04 28](https://github.com/twentyhq/twenty/assets/19412894/62e2ea21-a9e6-4f7d-802e-a712fa8c0254)

**Comment by FelixMalfait** [comment] 2024-04-22 08:25
@Bonapara got it thanks for the clarification! I think they are strongly related since most of the heavy work is creating the right view structure for options. Let's wait for https://github.com/twentyhq/twenty/issues/4244 to be complete before we tackle this one

**Comment by Bonapara** [comment] 2024-11-26 09:22
Deprecated

**Closed** 2024-11-26 09:21 UTC
Labels: scope: front, size: short
