### ISSUE TITLE
Optimistic rendering on notes & tasks

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2950] opened 2023-12-12 08:33 UTC
# Problem

The content of the note is not updated in real-time on its card preview:

https://github.com/twentyhq/twenty/assets/19412894/ccca8e2b-a96d-4b80-ae6f-36fbc85dff37

**Comment by Bonapara** [comment] 2023-12-12 08:34
@lucasbordeau WDYT? Is it optimistic rendering indeed?

**Comment by Kanav-Arora** [comment] 2023-12-12 08:34
Hi @Bonapara 
Can I work on this?

**Comment by Bonapara** [comment] 2023-12-12 08:35
Hi @Kanav-Arora! So faast! Sure, thanks 🙌

**Comment by Kanav-Arora** [comment] 2023-12-12 08:50
Hi @Bonapara 
Do we have any handler for optimistic updates or should I work on this from scratch?

**Comment by Bonapara** [comment] 2023-12-13 08:59
Hi @Kanav-Arora, I think @lucasbordeau will be more able to answer.

**Comment by Kanav-Arora** [comment] 2023-12-14 11:16
Hi @lucasbordeau 
Please suggest something on this

**Comment by charlesBochet** [comment] 2023-12-15 16:21
@Kanav-Arora This one is actually very tricky right now. We are still working on the optimistic rendering fundation that will make it easy. Let's hold a bit on this one!

**Comment by FelixMalfait** [comment] 2024-01-17 11:12
This seems to be fixed, I was not able to reproduce. Closing issue!

**Closed by FelixMalfait** 2024-01-17 11:12 UTC
Labels: type: bug, good first issue, scope: front, size: minutes
