### ISSUE TITLE
Multi-select values blink

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6011] opened 2024-06-25 08:38 UTC
# Bug Description

Multi-select values blink and are not registered when clicked to be selected or deselected.

https://github.com/twentyhq/twenty/assets/19412894/eb5dbb49-86c4-4a1c-8373-98e102140f52

**Comment by charlesBochet** [comment] 2024-07-01 15:54
+ Check sort behavior on Select

**Comment by ehconitin** [comment] 2024-07-25 07:31
Can  I work on this?

**Comment by Bonapara** [comment] 2024-07-25 07:50
@lucasbordeau will you handle it or can @ehconitin do it?

**Comment by ehconitin** [comment] 2024-07-25 08:03
@Bonapara , on a second thought let me finish my already assigned issues. If i get time Ill work on it. 
Sorry for the inconvenience.

**Comment by lucasbordeau** [comment] 2024-07-25 09:48
@Bonapara @ehconitin I'm currently quite busy with code review (including many from @ehconitin !) so I would be glad to let it to contributors.

**Comment by ehconitin** [comment] 2024-07-25 17:18
Hi @Bonapara, I could not reproduce this bug.
Worked fine for me.

https://github.com/user-attachments/assets/13fe8feb-82eb-49a1-9e14-6f6a440c0d6c

**Comment by Bonapara** [comment] 2024-07-26 08:18
Could not reproduce as well, @charlesBochet was it fixed?

**Comment by charlesBochet** [comment] 2024-08-14 15:03
Cannot reproduce either, let's close it

**Closed by charlesBochet** 2024-08-14 15:03 UTC
Labels: type: bug, scope: front, good for experienced contributor
