### ISSUE TITLE
In Darkmode fix white flash on page refresh

### ISSUE THREAD

**Issue by LumosViridi** [twentyhq/twenty#5295] opened 2024-05-05 15:24 UTC
## Bug Description

Fix blank white page that flashes on refresh when user has dark mode selected.

## Technical inputs

Confirmed on 

- Firefox for MacOS 125.0.3
- Chrome for MacOS 124.0.6367.119

**Comment by FelixMalfait** [comment] 2024-06-04 15:33
I guess this could probably fix it: https://github.com/twentyhq/twenty/issues/4914
The issue is probably that the user's settings need to be loaded and we're showing the skeleton loader before. Had we had the info in localStorage then we could use it at the top / in the skeleton loading

**Comment by FelixMalfait** [comment] 2024-11-28 14:08
Closing to just keep #4914 to track

**Closed by FelixMalfait** 2024-11-28 14:08 UTC
