### ISSUE TITLE
Initial Avatar sizing and centering

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3908] opened 2024-02-10 15:11 UTC
# Current Behavior

In the `account owner` field, initial avatars have different sizes and are not properly centered in the circle.

![CleanShot 2024-02-10 at 16 06 41](https://github.com/twentyhq/twenty/assets/19412894/6494d109-e6ed-4658-a2db-39cd06ee8db9)

# Desired behavior

![CleanShot 2024-02-10 at 16 10 52](https://github.com/twentyhq/twenty/assets/19412894/5f8de5a9-fea7-4e61-a256-b4b72c571028)

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=436-22577&mode=design&t=3YU6Q8yqMjgc6hbG-11

**Comment by prasannakarki77** [comment] 2024-02-10 16:26
I want to fix this issue. Could you assign this to me?

**Comment by Bonapara** [comment] 2024-02-10 16:32
Sure, done! Thanks @prasannakarki77 :)

**Comment by prasannakarki77** [comment] 2024-02-10 17:29
@Bonapara I checked the ui from app.twenty.com and didn't find any issues with the alignment or the size of the avatar text of the users I created. 

Also, if it is a confirmed issue and its urgent, please assign it to someone else because I am having trouble starting the server locally following the docs. "Error during Data Source initialization: AggregateError". I might need some time to figure out what went wrong. 

I am really sorry for the inconvenience. I should have first setup locally and then ask to be assigned. I will try to setup the project locally and go through it for a week and then start contributing to other new issues.


![image](https://github.com/twentyhq/twenty/assets/63549402/83fb7b1e-95cf-4e57-bffb-f9306cb46112)

**Comment by Bonapara** [comment] 2024-02-10 18:18
Hi @prasannakarki77, sorry I was not precise enough. This happens in the `Account Owner` field menu picker

**Comment by prasannakarki77** [comment] 2024-02-11 13:22
@Bonapara I am stuck trying to setup database and server locally on my windows even after following the docs. I think I will need some time to figure it out. I don't want this small issue to get stuck for days so I will unassign myself for now. It is a good first issue, so I don't want to hinder others from working on this just because it is assigned to me.
I figure out the setup and then look out for other small issue to get started. Sorry for the inconvenience.

**Comment by Bonapara** [comment] 2024-02-12 08:11
No worries, thank you @prasannakarki77!

**Comment by Bonapara** [comment] 2024-02-12 16:23
Done, thanks @tusharwebd!

**Comment by tusharwebd** [comment] 2024-02-13 17:12
While setting up the project initializing the server with `yarn nx database:init twenty-server`, I am getting the following errors:

```
Performed 'create function graphql' successfully
src/core/auth/services/auth.service.ts:13:43 - error TS2307: Cannot find module 'twenty-emails' or its corresponding type declarations.
13 import { PasswordUpdateNotifyEmail } from 'twenty-emails';
                                             ~~~~~~~~~~~~~~~
src/core/auth/services/token.service.ts:22:40 - error TS2307: Cannot find module 'twenty-emails' or its corresponding type declarations.
22 import { PasswordResetLinkEmail } from 'twenty-emails';
                                          ~~~~~~~~~~~~~~~
src/workspace/workspace-cleaner/crons/clean-inactive-workspace.job.ts:9:8 - error TS2307: Cannot find module 'twenty-emails' or its corresponding type declarations.
9 } from 'twenty-emails';
         ~~~~~~~~~~~~~~~
Found 3 error(s).

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target database:init for project twenty-server (31s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

Any suggestions on how to fix this? I tried hard coding the method import paths but that leads to more issues.

**Closed** 2024-05-16 15:38 UTC
Labels: good first issue, scope: front, size: minutes, type: design improvement
