### ISSUE TITLE
The menu that opens when you right click with the mouse in the companies table is not obvious.

### ISSUE THREAD

**Issue by HusemZ** [twentyhq/twenty#8341] opened 2024-11-05 13:33 UTC
![image](https://github.com/user-attachments/assets/f078a0b3-8bc7-45c2-9be1-380b9c29015a)

**Comment by AjayAdsule** [comment] 2024-11-05 14:48
can i work on this issue

**Comment by harshrajeevsingh** [comment] 2024-11-05 15:20
Can't reproduce on main. What browser are you using?

**Comment by Bonapara** [comment] 2024-11-06 08:26
Was able to reproduce on demo.twenty.com using Chrome

**Comment by FelixMalfait** [comment] 2024-11-18 09:39
Closing as this has been fixed! Thanks for the report

**Closed by FelixMalfait** 2024-11-18 09:39 UTC
Labels: type: bug
