### ISSUE TITLE
Open Last Seen View instead of the First View

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6125] opened 2024-07-04 08:30 UTC
# Current Behavior

When navigating to an object, the view that appears first in the view switcher opens.

https://github.com/twentyhq/twenty/assets/19412894/3aa76a29-cffa-4476-b1e3-8fa1d04ec4ca

# Desired Behavior

We should open the last seen view instead.

**Comment by FelixMalfait** [comment] 2024-07-10 08:20
Duplicate of https://github.com/twentyhq/twenty/issues/5949 - I'll close the older issue but you can refer to it for deeper technical instructions

**Comment by Faisal-imtiyaz123** [comment] 2024-07-19 17:06
@Bonapara May I work here.

**Comment by Bonapara** [comment] 2024-07-22 09:11
Hi @Faisal-imtiyaz123, this task is better suited for a more experienced contributor, but thanks for asking ;) I've assigned you to some other issues you commented on.

**Closed** 2024-08-28 15:15 UTC
Labels: scope: backend, size: hours, good for experienced contributor
