### ISSUE TITLE
Notes flash after note update/creation

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5444] opened 2024-05-16 14:23 UTC
# Description

Notes are flashing when creating or updating a note

https://github.com/twentyhq/twenty/assets/19412894/76d90c79-d913-42ea-80b1-e9cd479bda48

# Where

Twenty (demo) workspace

# How to reproduce

Go to a record page with existing notes and try to create a new one.

**Comment by H0onnn** [comment] 2024-05-21 08:31
Hello, @Bonapara ! Please check PR #5469 :)

**Comment by Bonapara** [comment] 2024-05-21 09:17
Hi @H0onnn, I'm not technical myself, but the tech team will look into it soon. Thanks!

**Comment by lucasbordeau** [comment] 2024-05-30 10:25
Can't reproduce on main closing for now, don't hesitate to re-open.

**Closed by lucasbordeau** 2024-05-30 10:25 UTC
Labels: type: bug, scope: front, good for experienced contributor
