### ISSUE TITLE
Encountered an error on login page

### ISSUE THREAD

**Issue by dearroy** [twentyhq/twenty#1971] opened 2023-10-11 13:22 UTC
## Bug Description

I encountered an issue with logging in after deploying a fresh installation on Render (main branch).

Entered the email address, and clicked 'continue', but nothing happened.

The console says `index.ts:97  Uncaught (in promise) ApolloError: Unexpected token '<', "<!doctype "... is not valid JSON`. 

![image](https://github.com/twentyhq/twenty/assets/4345183/ffbbde29-ad92-46ad-a73a-69c04ee21e52)

## Expected behavior

The login form should automatically transition to the password entry field.

## Device

MacOS 13.2.1, Microsoft Edge Version 117.0.2045.47

**Comment by khakimov** [comment] 2023-10-11 14:58
could it be caused by uBlock in your browser? 

> According to [the uBlock Origin issue report](https://github.com/uBlockOrigin/uBlock-issues/issues/2763) you can add the filter @@||localhost^$permissions=browsing-topics=() to your uBlock Origin filters to disable the messages. However it should have been fixed in uBlock Origin in [this commit](https://github.com/uBlockOrigin/uAssets/commit/63ad5d6f098c4e515ecbb6b89f6b3ff373c146bb)

**Comment by dearroy** [comment] 2023-10-11 15:04
> could it be caused by uBlock in your browser?
> 
> > According to [the uBlock Origin issue report](https://github.com/uBlockOrigin/uBlock-issues/issues/2763) you can add the filter @@||localhost^$permissions=browsing-topics=() to your uBlock Origin filters to disable the messages. However it should have been fixed in uBlock Origin in [this commit](https://github.com/uBlockOrigin/uAssets/commit/63ad5d6f098c4e515ecbb6b89f6b3ff373c146bb)

Nah I have already double-checked my uBlock panel to ensure that nothing is blocked on the site.

BTW I am not using localhost, as mentioned earlier, I am using Render with an external link.

**Comment by khakimov** [comment] 2023-10-12 02:45
> Nah I have already double-checked my uBlock panel to ensure that nothing is blocked on the site.
> 
> BTW I am not using localhost, as mentioned earlier, I am using Render with an external link.

could you check in **Network** what kind of requests going to the server (Headers and Payload), seems like instead of json graphql is getting html. It will help to replicate and understand the problem better. 

<img width="500" alt="image" src="https://github.com/twentyhq/twenty/assets/396223/7c86f4d2-d55e-416f-8c4b-aa929ef3b9c4">

**Comment by dearroy** [comment] 2023-10-12 03:19
> > Nah I have already double-checked my uBlock panel to ensure that nothing is blocked on the site.
> > BTW I am not using localhost, as mentioned earlier, I am using Render with an external link.
> 
> could you check in **Network** what kind of requests going to the server (Headers and Payload), seems like instead of json graphql is getting html. It will help to replicate and understand the problem better.
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/396223/274464937-7c86f4d2-d55e-416f-8c4b-aa929ef3b9c4.png">

Yeah, attached the screenshot.
![image](https://github.com/twentyhq/twenty/assets/4345183/6122d952-2f52-427b-9ce5-a4c02f26b1e9)

**Comment by dearroy** [comment] 2023-10-12 15:48
I managed to fix it by configuring the environment variables on both front and server, and re-deploying them.

So what I have found that can be improved:
1. The "metadata" scheme wasn't created automatically
2. The environment variables weren't correctly created automatically

**Comment by khakimov** [comment] 2023-10-14 11:48
thank you for pointing at the problem. already fixed and tested 🙏

> Here are some areas for improvement that I identified:
> 
> 1. The "metadata" scheme was not created automatically.
> 2. The environment variables were not correctly created automatically.

**Comment by charlesBochet** [comment] 2023-10-16 06:46
Closing this issue :)

**Closed by charlesBochet** 2023-10-16 06:46 UTC
Labels: type: bug
