### ISSUE TITLE
Bug[Two problems(1. symbol for currency is not showing for every currency 2. all the currency aren't in a alphabetical order)]

### ISSUE THREAD

**Issue by arg387** [twentyhq/twenty#8096] opened 2024-10-26 18:12 UTC
## Bug Description

1. Beside currency, symbol for currency is not showing for every currency
![Screen Recording 2024-10-26 232010](https://github.com/user-attachments/assets/c063bd80-bcf7-4035-abdd-474be09131cc)
![Screenshot 2024-10-26 230657](https://github.com/user-attachments/assets/6b16ddf0-12ba-45a4-8c12-0a93af317252)
2. all the currency aren't in a alphabetical order.
[screenshot]
![Screenshot 2024-10-26 231148](https://github.com/user-attachments/assets/c430ac1e-b8fa-4d2b-8a1b-130d8ba80fa6)
![Screenshot 2024-10-26 232127](https://github.com/user-attachments/assets/f40b8702-2b52-4c8f-8415-0d297e7b1c29)

**Example**
[LINK](https://demo.twenty.com/objects/opportunities?view=2e98bd24-94d1-439c-b641-0190c9e8a843)

## Expected behavior

1. Currency symbol is shown for every currency.
2. All Currency should be in an alphabetical order.(It is hectic to find a particular currency. It will be better to add a search bar with two rows showing currency in alphabetical order. ) 

## Points
50-150

**Comment by BOHEUS** [comment] 2024-10-26 18:43
1. Not every currency has the symbol in icon library used in project so currencies without symbol have generic IconCoins implemented (see #7038), also, currencies are not visible when selecting currency in Opportunities
2. These currencies are in alphabetical order based on currency code, not the currency's name, and there's search bar for them 
![image](https://github.com/user-attachments/assets/2b1ff9ef-4c2c-4c86-aba5-db4b312cac9f)

**Comment by arg387** [comment] 2024-10-26 19:54
![Screenshot 2024-10-27 011533](https://github.com/user-attachments/assets/931d4532-ee80-4976-a3fe-fa8399113315)
i have been using the demo app but There is no search option.

**Comment by BOHEUS** [comment] 2024-10-26 19:58
Then it seems it must be browser-related issue, what browser is it? Firefox nightly?

**Comment by arg387** [comment] 2024-10-26 20:00
firefox

**Comment by arg387** [comment] 2024-10-26 20:06
Search is not working if you don't scroll. But where is horizontal scroll bar? ?? I have been trying to scroll horizontally but somehow it is not working.
![Screen Recording 2024-10-27 012956](https://github.com/user-attachments/assets/4ba49aa7-ba7a-4155-9fb3-37068b7c85af)
Anyway i am using pure firefox.

**Comment by BOHEUS** [comment] 2024-10-26 20:10
Try checking this on different demo account, maybe it's because of overflowed left menu, I tried to reproduce it on different Firefox versions but with no luck

**Comment by arg387** [comment] 2024-10-27 01:45
where should i find different demo account??? There is only one available in your github repo.

**Comment by BOHEUS** [comment] 2024-10-27 06:06
Simply type other email address than provided in documentation, doesn't have to be your email address

**Comment by arg387** [comment] 2024-10-27 10:48
![Screenshot 2024-10-27 161500](https://github.com/user-attachments/assets/66dd0107-2aba-49fc-9457-905087db5a3f)
@BOHEUS  after using other demo account search bar is working. But The repository demo account still have the same problem.

**Comment by BOHEUS** [comment] 2024-10-27 18:39
So it's related to left menu overflow, probably will be resolved in #8063

**Comment by Bonapara** [comment] 2024-10-28 14:10
I will close this issue for now. Please open another dedicated issue because @BOHEUS is correct about point 1, and point 2 does not apply to all browsers. Thanks for creating the issue though!

**Closed by Bonapara** 2024-10-28 14:10 UTC
Labels: type: bug
