### ISSUE TITLE
Image Upload in Activity editor seems broken

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4160] opened 2024-02-23 16:47 UTC
### Image Upload

On a Task, open the activity editor.
The "Add image" > "Upload" feature seems to be broken

<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/c9078126-4794-40d0-b17e-53d5db0566ed">

### Paste image

Pasting image into the Activity Editor does not seem to persist the image

**Comment by sriram-V20** [comment] 2024-02-25 07:53
Hi @charlesBochet,
can I work on this issue ?

**Comment by charlesBochet** [comment] 2024-02-25 21:53
sure @sriram-V20, thank you!

**Comment by pojith** [comment] 2024-02-26 15:26
can i work this issues

**Comment by charlesBochet** [comment] 2024-02-26 21:43
@pojith I think @sriram-V20 is already working on it, let's wait a bit to see the PR :)

**Comment by pojith** [comment] 2024-02-27 01:30
ok

**Comment by charlesBochet** [comment] 2024-03-04 15:51
Unassigning it as we don't have any news from @sriram-V20

**Comment by kikoleitao** [comment] 2024-03-04 15:52
Hi @charlesBochet, can I work on this issue?

**Comment by charlesBochet** [comment] 2024-03-04 15:55
Sure, go ahead!

**Comment by kikoleitao** [comment] 2024-03-06 00:00
I have been able to reproduce the paste image bug like it was described by sriram-v20. Still, I haven't been able to pinpoint it in the code. @charlesBochet do you have any suggestions on how to approach this, given that the bug doesn't happen when we open the task after having another one opened, but it does when we close and re-open the task? Also, note that this rendering bug is exclusive to images, it doesn't happen with any other element (even uploaded files).

https://github.com/twentyhq/twenty/assets/92337535/766c9c7c-e44a-4d05-bbed-2f0fda9a1ff9

**Comment by charlesBochet** [comment] 2024-03-07 15:02
@kikoleitao I haven't had time to look in details what the issue is. Do you think it's related to Twenty implementation or to the library we are using?

**Comment by sriram-V20** [comment] 2024-03-08 17:23
@charlesBochet @kikoleitao I mentioned this is issue (Image upload being broken) in Blocknote Discord channel and I was asked to upgrade to V0.12, They resolved a similar issue https://github.com/TypeCellOS/BlockNote/issues/569.

**Comment by charlesBochet** [comment] 2024-03-08 17:49
interesting, let's upgrade and see if it fixes it

**Comment by kikoleitao** [comment] 2024-03-08 19:04
@sriram-V20 thank you! @charlesBochet, I tried the recommended version but ran into some errors when running twenty-front. Should I try to solve the problem with the current version of blocknote or refactor the code to use V0.12? 
[frontend_output.txt](https://github.com/twentyhq/twenty/files/14542190/frontend_output.txt)
![error](https://github.com/twentyhq/twenty/assets/92337535/32dd9d89-4479-4efc-94b4-f88f9dcb9463)

**Comment by brendanlaschke** [comment] 2024-03-20 07:47
I tested a bit and the problem seems to be the image dialog is closed before the browsers file dialog is closed. Also on the embed you can't click on something without the menu closing / losing focus...

**Closed** 2024-04-02 14:31 UTC
Labels: type: bug, good first issue, scope: front, ready, size: hours
