### ISSUE TITLE
"Regenerate Key" button creates a duplicate API key

### ISSUE THREAD

**Issue by AbuHafsa** [twentyhq/twenty#3956] opened 2024-02-13 20:49 UTC
## Bug Description

When creating an API key on the UI, and then clicking the "Regenerate Key" button, I notice a new key is created under Settings > Developers.

## Expected behavior

When clicking on "Regenerate Key" button, I do not want a duplication of the key but rather overwrite the same key.

**Comment by FelixMalfait** [comment] 2024-02-16 14:42
Thanks for the report! I can reproduce it

**Comment by sohalkumar** [comment] 2024-02-18 11:11
Hi @AbuHafsa & @FelixMalfait. I am very new to open source and was looking at this issue to contribute. I noticed that the duplicates **'go away' after a refresh** of the webpage.
I am still trying to understand the codebase and how the rendering is happening, hence I am unable to offer a solution yet.

**Comment by sohalkumar** [comment] 2024-02-20 04:57
Hi @FelixMalfait 

> So when we go back to the page that lists API Keys, Apollo doesn't call the server again.

This could also explain the reason that keys are not 'removed' from the table after we delete(disable) them. They are also only removed after a refresh. 


> Probably you can use `refetchQueries`. Might be something smarter to do but I'm not sure

I will try my best to look into it and possibly come up to a solution.

**Comment by charlesBochet** [comment] 2024-02-20 08:42
@FelixMalfait @sohalkumar  We don't have to use refetch query. It should be handled by the optimistic cache logic.

In the idea, the initial graphql query should be filtering on  revokedAt: null
When we update an API key (setting revokedAt to null), the updateObject function should call the triggerUpdateRecordOptimisticEffect. This code should see that the initial graphql is filtering on revokedAt, loop over the api key returned return and see that the updated api key no longer matches the request. The check logic is in isRecordMatchingFilter function

We might have a bug there!

**Comment by sohalkumar** [comment] 2024-02-21 14:38
Hi @charlesBochet 

> In the idea, the initial graphql query should be filtering on revokedAt: null When we update an API key (setting revokedAt to null), the updateObject function should call the triggerUpdateRecordOptimisticEffect. 

I looked at the `triggerUpdateRecordOptimisticEffect` function and I think I have found the bug.

```
const updatedRecordShouldBeAddedToRootQueryEdges =
            updatedRecordMatchesThisRootQueryFilter &&
            updatedRecordIndexInRootQueryEdges === -1;

```
```
const updatedRecordShouldBeRemovedFromRootQueryEdges =
            updatedRecordMatchesThisRootQueryFilter &&
            updatedRecordIndexInRootQueryEdges === -1;`

```
Both of these have the exact same logic which leads to the updatedRecord being added due to the logic in `updatedRecordShouldBeAddedToRootQueryEdges` and then removed due to `updatedRecordShouldBeRemovedFromRootQueryEdges`

What I propose is changing the `updatedRecordShouldBeRemovedFromRootQueryEdges` like so - 
```
const updatedRecordShouldBeRemovedFromRootQueryEdges =
            !updatedRecordMatchesThisRootQueryFilter &&
            updatedRecordIndexInRootQueryEdges !== -1;`

```

If I am going in the right direction please assign this issue to me.
Thanks.

**Comment by sohalkumar** [comment] 2024-02-21 19:11
> @sohalkumar I believe this has been fixed recently actually. Could you see if the issue still happens on main branch?

Yes the issue is fixed and there is no duplicates anymore but the modal(pop up) that asks for the confirmatioin does not go away even after typing yes and clicking on re generate. If I click out of it the regenetated key is not visible.

![image](https://github.com/twentyhq/twenty/assets/68388983/20fe5585-0f09-4a67-bd92-4b29227c4843)
clicked on re generate but still doesn't go away.

![image](https://github.com/twentyhq/twenty/assets/68388983/18c61fa2-bb29-4393-92a4-3c66aa1bb44e)
clicked outside the pop up and the key is gone

**Comment by FelixMalfait** [comment] 2024-02-22 13:55
oh good catch @sohalkumar can you try fixing that one then :)) ? Thanks!

**Comment by sohalkumar** [comment] 2024-02-22 15:42
Hi @FelixMalfait 
> oh good catch @sohalkumar can you try fixing that one then :)) ? Thanks!

`setIsRegenerateKeyModalOpen(false);`

adding this in the end of the `regenerateApiKey` function seems to work.

**Comment by sohalkumar** [comment] 2024-02-24 20:26
Hi @FelixMalfait 
> Would be best to manage this in `ConfirmationModal` to make sure it works for every new modal we create in the future :)

What I could think of is adding the following in the onClick of "Regenerate Key" button inside `ConfirmationModal` -
```
onClick={async () => {
              await onConfirmClick();
              setIsOpen(false);
            }} 
```
This works but there must, obviously, be a better approach but I can't seem to figure it out as of now :')

**Comment by charlesBochet** [comment] 2024-02-25 21:57
@sohalkumar The approach you describe seems to work! :) what's wrong with it?

**Comment by sohalkumar** [comment] 2024-02-26 01:55
Hello @charlesBochet 
> @sohalkumar The approach you describe seems to work! :) what's wrong with it?
I just thought there might be a better approach to solve this ^_^"
If this is alright , what are the next steps? Do I raise a PR?
Thanks :D

**Comment by sohalkumar** [comment] 2024-02-26 15:35
Hi @charlesBochet I just raised a PR. Please review it. 
Thanks :D

**Comment by charlesBochet** [comment] 2024-02-26 21:42
PR has been merged, thank you! Closing this issue

**Closed by charlesBochet** 2024-02-26 21:42 UTC
Labels: type: bug, good first issue

**Comment by sohalkumar** [comment] 2024-02-27 03:03
@charlesBochet 
Couldn't have been possible without your detailed responses and help.
Thank you.
