### ISSUE TITLE
Files are viewable from all people/companies

### ISSUE THREAD

**Issue by Der-Feind** [twentyhq/twenty#6289] opened 2024-07-16 14:34 UTC
## Bug Description

If I attach a file to a person or company, it is visible in other companies and people, too. Not only in the person, where the file is attached.

**Example:** 
```
I have a person and I want to attach a contract to him. I upload the file.
I change to another person, click on "Files" and the document from the person before is actually there, too.
```

## Expected behavior

Only show files in the attached person or company

**Example:** 

Only show files in the attached person or company

## Technical inputs

**Example:** 
```
None.
```

**Comment by Bonapara** [comment] 2024-07-16 15:30
Unable to reproduce. @Weiko, any ideas?

**Comment by FelixMalfait** [comment] 2024-07-17 08:56
I think we had that bug on Notes/Tasks but @lucasbordeau fixed it last week. @Der-Feind are you running on a self-hosted version? If yes you can upgrade to the latest version, it's likely to be fixed

**Comment by FelixMalfait** [comment] 2024-07-17 09:18
I'll close this but please let us know if you're able to reproduce on a fresh install

**Closed by FelixMalfait** 2024-07-17 09:18 UTC
Labels: type: bug
