### ISSUE TITLE
On Settings page, I see a DataModel nav leading to a data-model empty page

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#1810] opened 2023-10-02 13:10 UTC
Create a route + add a nav to the settings menu.
Only add title to the page

**Comment by thaisguigon** [comment] 2023-10-02 14:01
Duplicate of [#1760](https://github.com/twentyhq/twenty/issues/1760)

**Closed** 2023-10-02 14:02 UTC
