### ISSUE TITLE
Can't delete a Task with comment in it.

### ISSUE THREAD

**Issue by sriram-V20** [twentyhq/twenty#4233] opened 2024-02-29 01:58 UTC
I created a task and then made a comment in the comment section, after this I'm not able to delete this task. But I can delete other tasks which don't have comments in it.

Throws the following error in Server logs.
![image](https://github.com/twentyhq/twenty/assets/73017193/2cf05c08-4f56-4af4-a25f-d6fcc36b396b)

And strange thing is request gives 200 code but the response gives 500 code
![image](https://github.com/twentyhq/twenty/assets/73017193/ecb0fd63-7eea-4d96-8882-64b3e17744d3)
![image](https://github.com/twentyhq/twenty/assets/73017193/240fede3-894f-4819-9d45-f685257e3b6f)
![image](https://github.com/twentyhq/twenty/assets/73017193/e6cb5fcc-6817-428e-aba4-f0c461367cc3)

**Comment by sriram-V20** [comment] 2024-02-29 02:00
If this is a good issue for new comers then I would like to take this up.

**Comment by FelixMalfait** [comment] 2024-02-29 11:09
Thanks for the report @sriram-V20 I was able to reproduce it.

It would be great if you can raise a PR for it yes!

The short-term fix would be toadd `onDelete: RelationOnDeleteAction.CASCADE` on the `Activity` field annotations in `comment.object-metadata.ts`. But I notice there's also the `author` field that has the same issue and where we should also cascade deletion (because it's a non-nullable field).

But I think it wasn't the design choice to set a default value for deletion behavior, so what you can do instead is go to `ReflectRelationMetadata` and change `  onDelete?: RelationOnDeleteAction;` to `onDelete: RelationOnDeleteAction;`.
That will raise typescript error for every file where the deletion behavior was not set explicitely.

- You can leave MessageParticipant relation on Person as set Null on cascade (which was the default behavior)
- You can set cascade deletion on attachment for deleted opportunities

Thanks

**Comment by FelixMalfait** [comment] 2024-03-01 14:21
@sriram-V20 ok for you? Thanks 🙏

**Comment by sriram-V20** [comment] 2024-03-01 19:03
Hi @FelixMalfait 

Thank you for the detailed explanation. I understood most of it, I'm confused by the last 2 bullet points and I will try to understand them better and work on a PR.

**Comment by FelixMalfait** [comment] 2024-03-03 10:19
@sriram-V20 sorry for the added pressure but since this is a relatively important bug do you think you could raise a first PR today or tomorrow? Thanks a lot

**Comment by sriram-V20** [comment] 2024-03-03 10:53
Thanks for letting me know how critical this is. Since I'm still getting the hang of the codebase, I don't think I can get a PR ready that fast. It might be best if someone with more experience takes this on. I'd really like to see how they fix it and learn from it.

**Comment by rostaklein** [comment] 2024-03-14 20:18
Cant reproduce anymore :) Was it fixed in between?

**Closed** 2024-04-03 08:45 UTC
Labels: good first issue
