### ISSUE TITLE
Documentation: Contributor guide back button does not appear when going through a direct-link

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2053] opened 2023-10-16 09:46 UTC
## Bug Description

On https://docs.twenty.com, after clicking on a contributor guide such as frontend or backend, the navigation menu is updated to show links only related to that contributor guide. When you want to go back, you have a button on the top of the navbar that says "back to home", however this button is not displayed when you arrive on the guide through a link. You can also try to refresh the page to reproduce the issue

https://github.com/twentyhq/twenty/assets/1834158/4e2510c1-ff93-4683-a15f-86b3a90d17f3

In the video, around 0:09, I refresh my browser to make the button disappear 
(Also, it does not figure on the video but I've tried clicking on any other link inside of the guide navbar and it does not make the button appear)

## Expected behavior

The back button should still be visible after refresh or direct-link

cc @nimraahmed if you want to have a look 🙂

**Comment by nimraahmed** [comment] 2023-10-16 10:27
@Weiko thank you for pointing it out, i've been able to reproduce it. I'll work on it.

**Comment by nimraahmed** [comment] 2023-10-16 13:56
This seems to be a production issue. Everything works fine locally. Here's a video of me refreshing the (local) docs and you can see that the back button is still visible:

[local-docs.webm](https://github.com/twentyhq/twenty/assets/50912134/326f9cf3-62ee-4321-823a-a373c251cfbc)

Upon further testing, it seems like that refreshing the hosted docs, changes the URL, which is most probably why we can no longer see the back button. The same is the case with other files in the sidebar, too (i.e., their URL also seems to change). See the example attached below. Notice the URL at the bottom  - even though I'm hovering on "contributing" which should point to https://docs.twenty.com/contributor/frontend/basics/contributing, it points to https://docs.twenty.com/hosting/self-hosting. This is after I hit refresh.  

<img width="1154" alt="Screenshot 2023-10-16 at 6 43 36 PM" src="https://github.com/twentyhq/twenty/assets/50912134/fd6d8e8f-ce2a-4887-bdb8-59c54d65879b">

Another interesting thing is if you resize the screen such that the sidebar disappears and then resize it again to make it appear, you'll be able to see the back button again, as demonstrated here:

[hosted-docs.webm](https://github.com/twentyhq/twenty/assets/50912134/493cff25-a78c-4f99-8930-62900dfb2e9c)

from what I understand, this seems to be an issue related to trailing slashes: https://github.com/facebook/docusaurus/issues/5109

@charlesBochet @Weiko

**Comment by charlesBochet** [comment] 2023-10-16 15:57
To reproduce locally: from docs folder
```
yarn build
npm install --global serve
serve -s build
```

**Comment by nimraahmed** [comment] 2023-11-08 18:46
also fixed with docusaurus v3 update @charlesBochet

**Closed by nimraahmed** 2023-11-08 18:46 UTC
Labels: type: bug
