### ISSUE TITLE
Hide Scrollbar before Scroll on Detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8847] opened 2024-12-03 14:42 UTC
# Current behavior

The scroll bar is displayed before the user scrolls

![Image](https://github.com/user-attachments/assets/d3e79227-1009-42cc-adb5-bfaab3c1fe40)

# Desired Behavior

Display the scrollbar as soon the user starts scrolling but not before

**Comment by Bonapara** [comment] 2024-12-03 14:42
@lucasbordeau WDYT?

**Comment by khuddite** [comment] 2024-12-03 15:51
@Bonapara I can work on this once it's confirmed that this is the change we wanna make.

**Comment by harshit078** [comment] 2024-12-03 19:59
![Image](https://github.com/user-attachments/assets/26e30e33-7a86-4bce-8723-4eee2f7aa7ca)
@Bonapara Can't seem to reproduce it, the scrollbar only shows when the items exceed the given width

**Comment by khuddite** [comment] 2024-12-04 12:45
@harshit078 If I understand correctly, the issue is that we don't wanna display the scrollbar always but only while it's being scrolled. So basically we wanna display auto-hide for the scrollbar.

@Bonapara @lucasbordeau Please let me know if this is the change we wanna commit to.

**Comment by Bonapara** [comment] 2024-12-04 16:55
💯 Yes @khuddite!

**Comment by khuddite** [comment] 2024-12-04 16:58
@Bonapara Cool, you can assign it to me

**Comment by Lucifer4255** [comment] 2024-12-05 12:05
Hi @Bonapara @khuddite I have attempted a fix for this issue . Can you assign me too for this PR?
https://github.com/user-attachments/assets/cc58dd15-8a9f-42b1-b1b0-b48a05805581

**Comment by khuddite** [comment] 2024-12-05 13:16
> Hi [@Bonapara](https://github.com/Bonapara) [@khuddite](https://github.com/khuddite) I have attempted a fix for this issue . Can you assign me too for this PR? https://github.com/user-attachments/assets/cc58dd15-8a9f-42b1-b1b0-b48a05805581

@Lucifer4255 You can go for it, but I think your changes will have unwanted implications on other scrollbars.

**Comment by khuddite** [comment] 2024-12-05 19:35
@Lucifer4255 I've fixed the issue by introducing an additional prop because it has a bigger problem than it seemed to be. We can close out your PR.

**Comment by Lucifer4255** [comment] 2024-12-06 04:18
> @Lucifer4255 I've fixed the issue by introducing an additional prop because it has a bigger problem than it seemed to be. We can close out your PR.

@khuddite hi I saw your PR according to your previous comment  the additional prop will still affect all the components in which the scroll wrapper is used . In the codebase there is already a 'move' type which ensures the hiding scroll bar problem as it's an inbuilt for the overlaying scroll bars component I think we can skip introducing extra prop for this

**Comment by khuddite** [comment] 2024-12-06 13:26
I don't think I fully understand the intent of your changes. Can you elaborate on the difference between `move` and `scroll` for `autoHide` option? Also if we intended to disable `autoHide` for certain circumstances, how do we achieve that?

I think your code can be even simplified to `autoHide:  'move',` because when the scrollbar is hidden, there is no point in caring about the `autoHide` flag.

I firmly believe that `autoHide` and `visibility` should not be dependent on the same flag and that's why I ended up introducing an additional prop. Again, I agree my changes will affect scrollbars on other pages in a way that they will be auto-hidden while being scrolled because that's the default option. However, We can evaluate and adjust that behavior as necessary.

I will leave it to the core team to decide. @Lucifer4255

**Comment by Lucifer4255** [comment] 2024-12-06 18:20
well yeah we can altogether set it to move but lets see what the core team does

**Comment by ehconitin** [comment] 2024-12-20 14:27
closed in #8896

**Closed by ehconitin** 2024-12-20 14:27 UTC
Labels: scope: front, type: design improvement, for experienced contributor
