### ISSUE TITLE
blank screen after install docker compose from website

### ISSUE THREAD

**Issue by tod-zhang** [twentyhq/twenty#5184] opened 2024-04-26 07:48 UTC
![image](https://github.com/twentyhq/twenty/assets/74004482/248fd15c-2b8b-4f28-bd56-a09dc1d41523)

I use this code from website.
bash <(curl -sL https://git.new/20)

**Comment by hiteshsondhi88** [comment] 2024-04-26 09:36
Happened same here but you can set `SERVER_URL={your-domain}` to resolve the same

**Comment by tod-zhang** [comment] 2024-04-26 12:48
> Happened same here but you can set `SERVER_URL={your-domain}` to resolve the same

![image](https://github.com/twentyhq/twenty/assets/74004482/7c696c85-16a1-4b70-9ff6-2d7e71609552)
not work

**Comment by Mohamed-sobhi95** [comment] 2024-04-27 09:09
same issue

**Comment by ipuris** [comment] 2024-05-08 04:17
Same issue. I found some error messages here:

![image (2)](https://github.com/twentyhq/twenty/assets/2157657/422d42e2-3772-459e-9c01-5a85a626d278)

**Comment by christophschoeni** [comment] 2024-05-08 09:17
Same issue with Server Domain

**Comment by GijsSi** [comment] 2024-05-14 15:13
I found the solution to this. I did this via Portainer, pretty sure you can do it manually as well. 
![image](https://github.com/twentyhq/twenty/assets/21217320/1e4adf7d-bcbc-48c5-9ff5-b04f51e4ad8d)

**Comment by nickwild-999** [comment] 2024-06-17 21:16
> I found the solution, I got it working by via Portainer, pretty sure you can do it manually as well. But both marked urls should be changed to the new IP/Domain name. ![image](https://private-user-images.githubusercontent.com/21217320/330493136-1e4adf7d-bcbc-48c5-9ff5-b04f51e4ad8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NTkyNDMsIm5iZiI6MTcxODY1ODk0MywicGF0aCI6Ii8yMTIxNzMyMC8zMzA0OTMxMzYtMWU0YWRmN2QtYmNiYy00OGM1LTlmZjUtYjA0ZjUxZTRhZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIxMTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjkzZTg1MWZhYWEzNWQzYWJkOTdiNjZlMmU2NjExNTI3MjMxZTFhMTBjMDY4NzI1NzRlZjQ5ZDY3MjM5MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VHUpHvYe_EMFmrz4k4vT7HqMAP5ekHCF3p1ALUjnvY)

This fixed my problem. Man thanks @GijsSi

**Comment by MuratDoganer** [comment] 2024-07-11 16:37
Same issue, changing the url does not help

**Comment by EmaX093** [comment] 2024-07-23 20:16
Just change SERVER_URL in .env file and do a full docker restart

`docker compose down && docker compose up -d`

**Comment by Knowaaaa** [comment] 2024-08-31 19:45
> Just change SERVER_URL in .env file and do a full docker restart
> 
> `docker compose down && docker compose up -d`

I have found that this does not update the container. Seems like whatever is in my .env is permanent after I start the stack for the first time.

**Comment by Freebios** [comment] 2024-09-13 15:46
Hello there,

I'll try to assess the issue(s) 🙂 

@tod-zhang I notice that your SERVER_URL  has a domain configured, does it point to your backend, is your backend exposed on port 443 ? This is the URL that the frontend will use to connect to the backend.

@GijsSi by default you do no need to set the FRONT_BASE_URL variable, it is only useful for advanced usecase where you host the frontend in another location than the backend (eg. on a bucket), by default FRONT_BASE_URL is set to the same value as SERVER_URL. Since you got it working, you could stick with only the SERVER_URL defined! 

@Knowaaaa Docker compose should be able to see the change in the environment automatically and recreate the container, make sure to have an updated version of docker and docker compose.

I think that most of your issues are due to lack of documentation, I'll open a PR to make it clearer. If you have more details related to this issue to help us reproduce it please post it, otherwise if you need further assistance with setting up Twenty please checkout our Discord Server.

**Comment by FelixMalfait** [comment] 2024-11-28 12:52
Closing as there was no clear action item. We'll work on an admin panel to help make the setup easier by surfacing the env variables and potential issues (just merged a first PR related to that, will create more issues).

**Closed by FelixMalfait** 2024-11-28 12:52 UTC

**Comment by abdurrahmanarikan** [comment] 2025-01-19 14:34
This still happens, after follow 1-click solution:

<img width="491" alt="Image" src="https://github.com/user-attachments/assets/ec22d8a6-1163-4c3a-b195-0fd4e8af9222" />

for the record, the dot env file does not have 
FRONT_DOMAIN=localhost
FRONT_PORT=3000
FRONT_PROTOCOL=http
records initially, 

running 
docker down
docker system prune -a
docker volume rm {all volumes}

does not work

**Comment by abdurrahmanarikan** [comment] 2025-01-19 14:43
> Just a quick hint to people having updated the SERVER_URL, restarted the docker containers and still facing the issue: **make sure to clear your cache**. Took me a few minutes to figure out that that was the issue.

can you share how to do that ?

**Comment by abdurrahmanarikan** [comment] 2025-01-19 15:00
After adding SIGN_IN_PREFILLED=false into dot env, my problem has been resolved (docker)

**Comment by FelixMalfait** [comment] 2025-01-19 17:45
@abdurrahmanarikan thanks! Shouldn't be necessary in the latest docker compose. When we tag the next release (0.40) on Monday it should be fixed
