### ISSUE TITLE
Data Model -> "Add Field" blank until page is clicked 

### ISSUE THREAD

**Issue by gvkhna** [twentyhq/twenty#7314] opened 2024-09-28 14:43 UTC
Seems related to caching of the fields and field types. Sometimes it's faster than others, sometimes it can take more than a minute and ends up requiring a refresh.

1. Settings
2. Data Model Type
3. Add Field
4. *(Page doesn't load for a long time)*

**Comment by gvkhna** [comment] 2024-09-28 18:14
This is reproducible and turns out it is just a UI bug.

Steps to reproduce:
1. Refresh app
2. Settings -> Data Model
3. Add Field
4. Page is not loading...
5. Click on page, and page loads.

Once that click and the page is loaded then it seems to work fine. The relevant div has display: none !important until a click occurs on it.

**Comment by Bonapara** [comment] 2024-09-30 08:19
Cannot reproduce, could you share a video?

**Comment by gvkhna** [comment] 2024-09-30 18:21
Here you go.

https://github.com/user-attachments/assets/49df89d5-a9af-4059-9d12-b394e9df96d7

https://github.com/user-attachments/assets/932c6446-8bbd-49c8-bd14-a7e49a3ee9b8

Cursory glance suggests it's something to do with Suspense on the `SettingsObjectNewFieldStep1` component but not sure.

**Comment by Bonapara** [comment] 2024-10-02 07:26
I see, thanks you @gvkhna! Closing as duplicate of https://github.com/twentyhq/twenty/issues/6967

**Closed by Bonapara** 2024-10-02 07:26 UTC
Labels: type: bug
