### ISSUE TITLE
Shortcut bug on Tables

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#610] opened 2023-07-12 00:10 UTC
# Step to reproduce (sometimes happening on app-main)
1. Load Twenty direclty on Companies page /companies
2. Press GP
3. Press C
It comes back to Companies page. We want it to always create a company

(GC should be the shortcut to go to companies)

Hard to reproduce but definitely happening sometimes

___

# Update

Any "key sequence" shortcut will not be triggered if keys press interval is too short.

**Comment by deepaksing** [comment] 2023-07-13 17:58
@Bonapara, is this issue fixed. for me its creating new row.

**Comment by Bonapara** [comment] 2023-07-14 03:54
Hi @deepaksing, not on my side, did you try to reproduce it quickly? Did you refresh the page before trying it?

**Comment by deepaksing** [comment] 2023-07-14 05:30
Yes, i have refreshed the page and restarted the server also multiple times. 
I was able to reproduce the bug previously. But after i pulled new code it got fixed for me.

**Comment by lucasbordeau** [comment] 2023-07-19 17:43
Cannot reproduce

**Comment by Bonapara** [comment] 2023-07-20 00:50
@charlesBochet can reproduce it as well.

**Comment by charlesBochet** [comment] 2023-07-31 05:45
It looks like this is happening when typing fast

**Comment by FelixMalfait** [comment] 2023-09-15 07:06
I'm not sure we have a path for resolution for this. Could be linked to https://github.com/twentyhq/twenty/issues/462 (external dependency). Closing for now. Let's reopen if we think we have a path

**Comment by Bonapara** [comment] 2023-09-19 22:54
This issue is still on the agenda, and more general that initially thought:
When you press two keys in a short interval (too fast), such as `G` then `P`, the shortcut is not triggered.

**Comment by FelixMalfait** [comment] 2024-01-17 13:26
Closing this one as the lib was updated. There are new bugs that were introduced on shortcuts so we probably need to do a bigger workstream on shortcuts at some point to improve stability / add testing

**Closed by FelixMalfait** 2024-01-17 13:26 UTC
Labels: type: bug, scope: front, ready, size: unknown
