### ISSUE TITLE
ApolloError: useFindManyRecords for "messages" not supported

### ISSUE THREAD

**Issue by marcelocbf** [twentyhq/twenty#7542] opened 2024-10-09 13:04 UTC
## Bug Description

Emails related to a person do not load.
Version: 0.31.0 Cloud

**Example:** 
```
Going into a person -> Emails tab -> Clicking on any email gives me the following error: "useFindManyRecords for "messages" error : ApolloError: This relation isn't supported by given find operator"
```
![Screenshot 2024-10-09 at 8 54 07 AM](https://github.com/user-attachments/assets/8ac55a76-b13f-483d-9476-f8799c9f37f4)

## Expected behavior

Be able to load and view the email content (It should not be a permission issue as the logged user is the same as the person trying to view the email)

**Comment by bosiraphael** [comment] 2024-10-14 08:34
Hello @marcelocbf, do you still have the issue? I couldn't reproduce the bug.

**Comment by FelixMalfait** [comment] 2024-10-14 09:22
@bosiraphael https://twenty-v7.sentry.io/issues/5664401981/?project=4507072499810304&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20user.email%3Amarcelocbf%40outlook.com&referrer=issue-stream&statsPeriod=7d&stream_index=0

<img width="915" alt="Screenshot 2024-10-14 at 11 22 41" src="https://github.com/user-attachments/assets/1b02d1c9-0c2a-4e98-8139-8451170e83c9">

**Comment by FelixMalfait** [comment] 2024-10-19 08:55
Closing in favor of #7830 which is more detailed

**Closed by FelixMalfait** 2024-10-19 08:55 UTC
Labels: type: bug, scope: backend, prio: high
