### ISSUE TITLE
[🕹️]Like & Re-Tweet oss.gg Launch Tweet

### ISSUE THREAD

**Issue by Rahul-Roy-Hub** [twentyhq/twenty#7961] opened 2024-10-22 14:49 UTC
### What side quest or challenge are you solving?

Retweeted Launch Post

### Points

50 Points

### Description

Retweeted Launch Post

### Provide proof that you've completed the task

![Like   Re-Tweet oss gg Launch Tweet](https://github.com/user-attachments/assets/0a566ffa-65a5-4bd2-bfe0-4f4cb89b4dd8)

**Comment by Bonapara** [comment] 2024-10-22 15:15
Duplicate of https://github.com/formbricks/formbricks/issues/3977

**Closed by Bonapara** 2024-10-22 15:15 UTC
Labels: 🕹️ oss.gg
