### ISSUE TITLE
New Install - Front end is blank

### ISSUE THREAD

**Issue by zamclachia** [twentyhq/twenty#5233] opened 2024-04-30 19:49 UTC
## Bug Description

I have installed TWENTY on an ubuntu server using the provided script: bash <(curl -sL https://git.new/20).
When I try to enter site localhost:3000, the browser tab indicates 20 Twenty, however the browser page is blank. 
![image](https://github.com/twentyhq/twenty/assets/4174668/26194637-b8bb-4e4a-8c80-3473f79733cf)

**Comment by darekdesu** [comment] 2024-04-30 23:31
Looks like duplicate of: https://github.com/twentyhq/twenty/issues/5229

Check your `.env` file and make sure `SERVER_URL` is set there and then restart the docker (`docker compose up -d` again).

**Comment by FelixMalfait** [comment] 2024-07-10 09:46
Sorry for the late reply! Thanks @darekdesu for replying. 
A PR to clarify what would have helped you in the docs is most welcome :))
Thanks a lot https://github.com/twentyhq/twenty/tree/main/packages/twenty-website/src/content/developers/self-hosting

**Closed by FelixMalfait** 2024-07-10 09:46 UTC
Labels: type: bug
