### ISSUE TITLE
Settings button occlusion when workspace and favorites tabs are expanded in sidebar

### ISSUE THREAD

**Issue by giiger** [twentyhq/twenty#8598] opened 2024-11-19 19:10 UTC
## Bug Description

In the main page of the application, when the favorites tab is expanded with many favorited items as well as the workspace tab being expanded, the settings button becomes inaccessible. This could cause confusion for new users looking for the settings button who don't know where it is located. 
Before occlusion:
![Image](https://github.com/user-attachments/assets/bc3322e7-4a15-46f9-8340-b9a032dea984)

After occlusion: 
![Image](https://github.com/user-attachments/assets/8d678d14-45c8-44fa-a5c8-a0e606509b22)

## Expected behavior

The Favorites and/or workspace tabs should limit the height at which it can expand in the sidebar so that the settings button never disappears from view. This could be done by adding a scroll bar for the overall sidebar, or by adding a max height to the container that doesn't overlap with the settings button.

**Comment by khuddite** [comment] 2024-11-20 14:09
@Bonapara 
![Image](https://github.com/user-attachments/assets/a38e92d4-0149-424a-999e-bb5150bd82c5)

I am no longer able to reproduce the issue on my end. Could you verify if it's already fixed? Thanks

**Comment by Bonapara** [comment] 2024-11-20 17:31
Cannot reproduce too - @giiger what version are you using?

**Comment by ehconitin** [comment] 2024-11-22 12:54
This was fixed @Bonapara

**Comment by Bonapara** [comment] 2024-11-22 13:56
Closing the issue then - Thanks @ehconitin

**Closed** 2024-11-22 13:56 UTC
Labels: scope: front, size: short, type: design improvement, for experienced contributor
