### ISSUE TITLE
/rest/batch/people very slow response when payload incorrect

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5523] opened 2024-05-21 22:05 UTC
## Bug Description

**Example:** 
```
export async function main(twenty_api_key: string, data: Array) {
  const url = 'https://api.twenty.com/rest/batch/people';
  const options = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Authorization': `Bearer ${twenty_api_key}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data[0])
  };
  const response = await fetch(url, options);
  return await response.text()
}


data =
[
  {
    "email": "koz@bionluk.com",
    "jobTitle": "Angel Investor",
    "lastName": "Koz",
    "firstName": "Muenif",
    "linkedinLink": {
      "url": "http://www.linkedin.com/in/munifkoz",
      "label": "LinkedIn"
    }
  }
]
```

As you can see, firstname and lastname are put incorrectly.

I get a 520 but it takes minutes to get back an answer. Which is pretty slow

## Expected behavior

Quicker response

**Comment by FelixMalfait** [comment] 2024-05-22 05:31
@martmull would you have any idea where this could come from? It seems 200 for batch response are very fast but 500 are slow. I would have expected the opposite as 200 involves writing to the DB and doing more things

**Comment by martmull** [comment] 2024-06-16 07:09
ran
```
const data =
  [
    {
      "email": "koz@bionluk.com",
      "jobTitle": "Angel Investor",
      "lastName": "Koz",
      "firstName": "Muenif",
      "linkedinLink": {
        "url": "http://www.linkedin.com/in/munifkoz",
        "label": "LinkedIn"
      }
    }
  ]

const api_key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDM0NWFjMy1iNGNiLTQwYmMtODVhMC1hZWQ2YWVkZDBmYzgiLCJpYXQiOjE3MTg1MjE2NjcsImV4cCI6NDg3MjEyMTY2NiwianRpIjoiOTYwMjRiNTktMjk3NS00ZTczLWEwZjItNTEzMDkzMjYxYzQxIn0.peJTwvYCNK1WFO-N14qQ8s8Qje04CNglwk4j4qyc8m8'

const url = 'https://api.twenty.com/rest/batch/people';
const options = {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Authorization': `Bearer ${api_key}`,
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(data[0])
};
const startTime = Date.now()
fetch(url, options).then((response)=>
{
  response.text().then((data)=> {
    console.log(data);
    console.log(Date.now()-startTime)
  })
});
```

Result:
```
{"statusCode":400,"message":"[\"Variable \\\"$data\\\" got invalid value { position: \\\"first\\\", email: \\\"koz@bionluk.com\\\", jobTitle: \\\"Angel Investor\\\", lastName: \\\"Koz\\\", firstName: \\\"Muenif\\\", linkedinLink: { url: \\\"http://www.linkedin.com/in/munifkoz\\\", label: \\\"LinkedIn\\\" } }; Field \\\"lastName\\\" is not defined by type \\\"PersonCreateInput\\\". Did you mean \\\"name\\\"?\",\"Variable \\\"$data\\\" got invalid value { position: \\\"first\\\", email: \\\"koz@bionluk.com\\\", jobTitle: \\\"Angel Investor\\\", lastName: \\\"Koz\\\", firstName: \\\"Muenif\\\", linkedinLink: { url: \\\"http://www.linkedin.com/in/munifkoz\\\", label: \\\"LinkedIn\\\" } }; Field \\\"firstName\\\" is not defined by type \\\"PersonCreateInput\\\".\"]","error":"Bad Request"}
557
```

**Comment by martmull** [comment] 2024-06-16 07:16
can't reproduce

**Comment by martmull** [comment] 2024-06-17 08:35
Closing for now, please don't hesitate to reopen the issue if the pb persists, I might miss something when trying to reproduce

**Closed by martmull** 2024-06-17 08:35 UTC
Labels: type: bug, T
