### ISSUE TITLE
Using "+" as a filter is breaking the table view

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#5387] opened 2024-05-13 15:07 UTC
## Bug Description

Special characters such as "+" have special meanings in Regex expressions. Using those in a filter breaks the filtering.

<img width="1274" alt="Screenshot 2024-05-13 at 17 05 23" src="https://github.com/twentyhq/twenty/assets/1834158/2e55f267-1c69-4702-a2c9-479de7fc1c6e">

## Expected behavior

Should filter with existing records regardless of the usage of special characters

## Technical inputs

Check isMatchingStringFilter.

**Comment by suman-somu** [comment] 2024-05-29 12:47
It didn't got error but unexpected behaviour.
[Screencast from 2024-05-29 18-08-31.webm](https://github.com/twentyhq/twenty/assets/75962762/73a45c48-7f67-4f53-87ec-15d9afdfaea0)

**Comment by FelixMalfait** [comment] 2024-07-10 09:35
Thanks @suman-somu! I'm also unable to reproduce the issue so I will close this, it has probably been fixed...

**Closed by FelixMalfait** 2024-07-10 09:35 UTC
Labels: type: bug, good first issue
