### ISSUE TITLE
Exclude Soft-Delete Page from Last Seen View

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6786] opened 2024-08-29 15:20 UTC
# Current behavior

By default, we now display the last seen view when navigating back to an object. 

**This included the soft-delete view**

https://github.com/user-attachments/assets/85170e9e-8296-454f-9d7b-a5d6a433d021

# Desired Behavior

The soft-delete page should not be considered as the last seen view, Instead, we should ideally redirect to the view displayed before the soft-delete page. In the worst case, redirect to the "All records" view.

**Comment by Bonapara** [comment] 2024-08-29 15:20
@lucasbordeau FYI

**Comment by Nabhag8848** [comment] 2024-08-29 16:53
Thanks, will take this up. after completion of my draft prs, do assign.🔥

**Comment by Bonapara** [comment] 2024-08-30 15:03
Sure @Nabhag8848, thanks for contributing!

**Comment by Nabhag8848** [comment] 2024-08-31 08:39
@Bonapara I need more clearity on what you meant from **soft-delete page should not be considered** .

- So when, we click on deleted companies to view previously deleted companies by deletedAt which can be filtered.  it works as similar to filter but at that point we haven't created a view. the demo you shared has same - the view isn't created. All that we show when navigating back to the object was persisted toggle which isn't related to last seen view cause that navigated to All in your demo which was the view, will be more clear with following demo: 

https://github.com/user-attachments/assets/efb7c6f1-8586-49d8-be94-1acfb08c51e3

- Also When we will navigate to different view having that toggle deleted companies - state where we haven't created new view yet that toggle is being persisted across the view of object, this is current behaviour and not just with soft delete but filter and sort too,just refresh that toggle will be gone or close and open twenty without any path.


https://github.com/user-attachments/assets/6eea7608-6cec-497d-8c1f-3f9f8d7f8b61


https://github.com/user-attachments/assets/ecffc66f-4f32-4f14-a5b7-7e2f6757e4a6

- So with this, what we are looking for ? how we need to handle those toggles ?  or Am i missing anything ? lemme know, thanks.

**Comment by charlesBochet** [comment] 2024-09-01 11:26
@Bonapara I cannot reproduce either, the current behavior described by @Nabhag8848 looks good to me. Could you give more details?

**Comment by Bonapara** [comment] 2024-09-02 09:04
Thanks, @Nabhag8848, for your valuable input.

We should remove the temporary filter autosave when someone exits a view. For example, if I apply a filter on the `People > Suppliers` view and then switch to the `People > Customers` view, the filter should be removed when I return to the `People > Suppliers` view.

However, we want to ensure the filter remains active while still within the context of the view. For instance, if I access a detail page from a temporarily filtered view, I don't want to lose my filters when I return to the list view from the detail page.

**Comment by Nabhag8848** [comment] 2024-09-06 08:06
@Bonapara I think this can be closed as resolved by changes within #6897

**Closed** 2024-09-06 08:08 UTC
Labels: scope: front, size: hours, good for experienced contributor
