### ISSUE TITLE
Line breaks in Tooltips

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8770] opened 2024-11-27 09:14 UTC
## Scope & Context

Tooltips do not display line breaks currently

## Current behavior

![Image](https://github.com/user-attachments/assets/06c16fc6-e714-4b8b-9f70-48e61aa23e78)

## Expected behavior
Linebreaks should be taken into account in tooltips. 

## Technical inputs

- Add an option on the tooltip component to allow line breaks display or not
- Allow this option on the all tooltips by default

Request from @Bonapara

**Comment by muraliSingh7** [comment] 2024-12-01 09:06
@charlesBochet If the PR has been merged and the issue is resolved, could you please close it? It would help reduce unnecessary open issues. Alternatively, if there’s a workflow or process for closing issues after a merge, could that be added?

**Comment by Bonapara** [comment] 2024-12-02 08:17
Thanks, @muraliSingh7, for noticing it.

**Closed** 2024-12-02 08:16 UTC
Labels: good first issue
