### ISSUE TITLE
Email updates are not properly rendered in timeline

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#7197] opened 2024-09-23 07:55 UTC
## Bug Description

When adding a secondary email, it appears in brackets with each letter separated. It should appear on a chip like the first email.

https://github.com/user-attachments/assets/2c66563d-d721-4a86-bcf0-b8f8ab589385

When adding an email, an empty array is added behind:

![CleanShot 2024-09-23 at 11 20 12](https://github.com/user-attachments/assets/097f704b-5d6a-473b-b8d6-5ced813220d4)

When removing an email, the empty array stays:

![CleanShot 2024-09-23 at 11 21 12](https://github.com/user-attachments/assets/7fa59717-bd96-424f-930f-3588ef6d33f0)

**Comment by Bonapara** [comment] 2024-09-23 09:23
This bug is related to the introduction of #6261

**Comment by sikehish** [comment] 2024-10-01 17:50
I would love to take this up. Would love to be assigned this task!

**Comment by Bonapara** [comment] 2024-10-01 19:49
/oss.gg 150

**Comment by Bonapara** [comment] 2024-10-01 19:49
Sure @sikehish, thanks for contributing!

**Comment by sikehish** [comment] 2024-10-02 10:17
Hi. Thank you for the opportunity! While I did run into this issue on demo.twenty.com, I am not able to reproduce the same on my local setup.
https://github.com/user-attachments/assets/5439e563-1ab5-403b-b382-5787c97cc094

Would be very grateful if I could some guidance on this.

I am also getting these TS related errors on my console.
![image](https://github.com/user-attachments/assets/ad34780b-6661-4af8-9a9e-e7e092a0e9ca)

**Comment by Bonapara** [comment] 2024-10-02 13:59
Hi @sikehish, you can ask on our Discord #Help channel. Thanks!

**Comment by thomtrp** [comment] 2024-10-08 08:41
@sikehish you need to have the worker running locally to create timeline activities.
Run the command `yarn nx worker twenty-server`

**Closed** 2024-10-08 13:48 UTC
Labels: type: bug, good first issue, scope: front, size: short, type: design improvement, prio: high
