### ISSUE TITLE
Add Filter View ability for Multi-Select field

### ISSUE THREAD

**Issue by gvkhna** [twentyhq/twenty#7313] opened 2024-09-28 14:39 UTC
Currently Objects can be filtered by a Select field. But not a multi-select field.

**Comment by Bonapara** [comment] 2024-09-30 08:24
Thanks for mentioning this, @gvkhna. We should prioritize it. (@charlesBochet)

**Comment by charlesBochet** [comment] 2024-10-09 16:12
Duplicate of https://github.com/twentyhq/twenty/issues/5358, closing :)

**Closed by charlesBochet** 2024-10-09 16:12 UTC
Labels: scope: back+front, type: feature, size: short, prio: high
