### ISSUE TITLE
self-hosting docker compose guide not working

### ISSUE THREAD

**Issue by maikroservice** [twentyhq/twenty#9047] opened 2024-12-12 20:00 UTC
## Bug Description

When following the manual docker compose setup guide (https://twenty.com/developers/section/self-hosting/docker-compose) on either ubuntu 22.04 or 24.04/debian12 in the cloud (hetzner/digitalocean) the application is running but when opening the `$SERVER_URL` the app shortly shows the interface and then promptly forwards to `localhost` instead of `$server_url`. This breaks the ability of the user to login/start using twenty.

 <img width="988" alt="Image" src="https://github.com/user-attachments/assets/a3986396-8ffe-4087-9e6c-38934fe06357" />

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/0c54bae2-37ea-45f0-8bf6-3fa47bd7d2af" />

.env:
<img width="754" alt="Image" src="https://github.com/user-attachments/assets/913b0ae7-4f11-43de-8081-870ec27ad769" />

## Expected behavior

The application should not forward to localhost for anything if this is not set in the .env file as the `$SERVER_URL`

**Comment by chrisjenx** [comment] 2024-12-12 20:36
Dupe of #9031

**Comment by maikroservice** [comment] 2024-12-12 20:38
> Dupe of #9031 

I don't think so, this is for 0.32 and for a fresh install not for an update

**Comment by FelixMalfait** [comment] 2024-12-13 10:36
Hey @maikroservice sorry we'll release 0.34.1 today which will fix this. It is indeed related to the issue @chrisjenx linked - if you set the variables correctly it should work (maybe in your case it wasn't taken into account because you didn't restart the server or something like that?)

**Comment by FelixMalfait** [comment] 2024-12-13 16:56
0.34.1 is published! Closing but let us know if you still face issues

**Closed by FelixMalfait** 2024-12-13 16:56 UTC

**Comment by chrisjenx** [comment] 2024-12-13 18:25
Fixes the Frontend issue, but looks like bad migration still: ![Image](https://github.com/user-attachments/assets/3db7dfa4-76d3-4aae-bd68-c326e9b66b3e)

**Comment by maikroservice** [comment] 2024-12-13 22:23
for me the server container does not start anymore when using 34.1

I would ask to reopen the issue if possible, because now its more broken than before 🙈

 <img width="753" alt="Image" src="https://github.com/user-attachments/assets/31b032cc-4938-49a9-9a75-df13ee5f36ba" />

**Comment by FelixMalfait** [comment] 2024-12-16 09:52
Hey @maikroservice the first error means you don't have the right PG_DATABASE_URL, this is because your PG_DATABASE_HOST contains a port, we'll fix that in the example file!
