### ISSUE TITLE
Overlaying shortcuts for specific object's record tabs

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7928] opened 2024-10-21 19:22 UTC
## Bug Description

Right now, if 2+ objects start with the same letter, the shortcut for them will be the same but after pressing keys for shortcut, app will move user to record tab of first object in lexicographical order (e.g. if there's object `uu` and `uu2`, shortcut `g+u` will always move to `uu`)
![image](https://github.com/user-attachments/assets/e4d281ab-f48b-4995-b4c3-756a5e127e59)

## Expected behavior

User should have an ability to customize the shortcut in such situation in Data Model?

**Comment by Bonapara** [comment] 2024-10-22 14:43
Thanks @BOHEUS! Duplicate of https://github.com/twentyhq/twenty/issues/7503

**Closed by Bonapara** 2024-10-22 14:43 UTC
Labels: type: bug
