### ISSUE TITLE
"New Row" Button Should Open First Column Input

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#2391] opened 2023-11-07 17:45 UTC
# Current behavior

Click on "+", then enter a record name. (2 steps required)

# Desired behavior

- Clicking the **+** button should immediately focus on the first field.
- Do not save the new row if the newly opened field is not filled. (If the first field is closed without being filled)· don't display empty rows.

![CleanShot 2023-11-07 at 18 37 28](https://github.com/twentyhq/twenty/assets/19412894/33958699-b5bf-4db5-b086-be5230d9ed98)

**Comment by uwemneku** [comment] 2023-11-13 17:17
Hi @Bonapara, please can this be assigned to me

**Comment by Bonapara** [comment] 2023-11-14 08:20
Thanks @uwemneku, just assigned you!

**Comment by Bonapara** [comment] 2023-12-15 17:33
Hi @uwemneku, are you still on this one? :)

**Comment by FelixMalfait** [comment] 2023-12-25 17:13
@Bonapara is this a duplicate of https://github.com/twentyhq/twenty/issues/3069? I'm closing it but please re-open if it's not!

**Closed by FelixMalfait** 2023-12-25 17:13 UTC
Labels: good first issue, scope: front, size: hours

**Comment by Kanav-Arora** [comment] 2023-12-25 17:18
> @Bonapara is this a duplicate of #3069? I'm closing it but please re-open if it's not!

Hi @FelixMalfait 
Its same and completed

**Comment by FelixMalfait** [comment] 2023-12-25 17:18
Great thanks!
