### ISSUE TITLE
Fix total count in show page navigation bar when total count = 1

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#6405] opened 2024-07-25 10:02 UTC
## Bug Description

Total count is displayed as 0 if it is 1.

![image](https://github.com/user-attachments/assets/1be1b002-2d91-43be-968d-c4ee7a0a8ee1)

## Expected behavior

Total count should be 1 if total count is 1.

## Technical inputs

See related issue : https://github.com/twentyhq/twenty/issues/6325

**Comment by ehconitin** [comment] 2024-07-25 12:21
@lucasbordeau can I work on it?

**Comment by ehconitin** [comment] 2024-07-25 15:05
Hi @lucasbordeau,
 I tried to reproduce the bug you mentioned but was unable to do so. Could you please provide more specific details or steps to replicate the issue? This would greatly help me in understanding and resolving the problem.

**Comment by charlesBochet** [comment] 2024-07-30 13:30
Updating the logic to:
  // Todo: the totalCount is broken on backend (likely because of pg_graphql)
  // Here are the current behavior, if the query does not return any result, totalCount is 0
  // If the query returns a result, totalCount is the total number of records
  const totalCount =
    totalCountBefore === 0
      ? totalCountAfter === 0
        ? 1
        : totalCountAfter
      : totalCountBefore;

We need to fix the BE, but this fix will do it in the FE

**Comment by prateekj117** [comment] 2024-07-30 14:45
@charlesBochet Can i take this up? I can replicate this.
<img width="1134" alt="Screenshot 2024-07-30 at 8 14 58 PM" src="https://github.com/user-attachments/assets/c1a1c924-42e1-4358-9035-7297c84403f9">

**Comment by Bonapara** [comment] 2024-07-30 15:54
@ehconitin sure you can have a try! Thanks for contributing again ;)

**Closed** 2024-07-30 17:16 UTC
Labels: type: bug
