### ISSUE TITLE
Fix record label identifier

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6215] opened 2024-07-11 08:30 UTC
It doesn't seem like the right record label identifier is displayed:

<img width="564" alt="Screenshot 2024-07-11 at 10 28 51" src="https://github.com/twentyhq/twenty/assets/6399865/39721b37-5736-4440-a156-fedad3d61734">

<img width="540" alt="Screenshot 2024-07-11 at 10 29 37" src="https://github.com/twentyhq/twenty/assets/6399865/cd243024-1061-43cc-ae29-ed946fd6b973">

**Comment by Bonapara** [comment] 2024-07-11 08:53
Duplicate of https://github.com/twentyhq/twenty/issues/6143

**Comment by FelixMalfait** [comment] 2024-07-14 16:55
We weren't talking exactly about the same thing - I was talking about the dropdown below, but thanks for referencing the issue, I agree we should keep just one. I talked to @Weiko and I believe his PR will fix both

**Closed** 2024-08-30 13:17 UTC
Labels: type: bug, T
