### ISSUE TITLE
On RecordTable, fix the first column freeze glitches

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3250] opened 2024-01-05 09:53 UTC
## Bug Description

1) On Record table, when I have more rows than the the view can show, and I scroll down, the first column is switching in "freeze" state. It should not, it should only on horizontal scroll
<img width="425" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/dacc2e1f-72c6-4a8f-8f5c-14c926b91c47">

2) Also, when I zoom out, all borders are not displayed (see screenshot above)

**Comment by ARSHIL1804** [comment] 2024-01-14 04:43
@charlesBochet I would like to work on this. Please assign it to me

**Comment by charlesBochet** [comment] 2024-01-14 09:28
Sure :) Thank you!

**Comment by FelixMalfait** [comment] 2024-01-25 16:59
This is a duplicate of https://github.com/twentyhq/twenty/issues/3346 which has just been fixed by @lucasbordeau

**Closed by FelixMalfait** 2024-01-25 16:59 UTC
Labels: type: bug
