### ISSUE TITLE
When I refresh removed filters are back

### ISSUE THREAD

**Issue by pombredanne** [twentyhq/twenty#4633] opened 2024-03-24 08:33 UTC
Using 0.3.3 hosted:

- On the people list I create a filter by name.
- Then I remove it (click the x)
- Then I press F5: the removed name filter is back

**Comment by charlesBochet** [comment] 2024-03-24 12:31
@pombredanne Thanks for raising an issue.
I cannot reproduce on my end. Maybe it's because of a confusion on the product:
- filters and sorts changes are persisted only when you hit "Update View" button. If you make changes but don't save them they won't be persisted.
<img width="1418" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/1b1f2df4-515e-4671-9987-b298104a4917">

We do that because as views are shared between workspace members, it would be painful to impact others when you want to look for something temporarily

**Comment by FelixMalfait** [comment] 2024-03-24 21:03
Yes! Closing the issue since I don't think it's a bug but feel free to send suggestion if you feel that we should have presented this in a different way, considering the context Charles gave above.
copying @Bonapara who leads product/design fyi

**Closed by FelixMalfait** 2024-03-24 21:03 UTC

**Comment by pombredanne** [comment] 2024-03-25 07:11
This is fairly confusing as it is IMHO. The general behavior of the app UI is that things are saved as soon as entered. Here there is a level of extra indirection where I would need to somehow, as an exception apply something?

Also I was expecting my UI settings to be mine and not impact everyone or be shared. See for instance Google docs spreadsheet filters with 1. filters that are global 2. filter views that are personal.

Whatever design you may want to drive towards, my point is that the current behavior is not obvious at all and I feel it may not be consistent with the rest of the UX.

**Comment by Bonapara** [comment] 2024-03-25 09:22
Thank you for your feedback, @pombredanne. We understand the confusion and are working towards separating team views into settings and personal views within the app to eliminate this issue at some point.
