### ISSUE TITLE
Replications in Kanban Modus

### ISSUE THREAD

**Issue by gabriel-morais** [twentyhq/twenty#4793] opened 2024-04-03 19:36 UTC
## Bug Description

Replications in the "Opportunities" page in Kanban Modus.
>>objects/opportunities

<img width="372" alt="Bildschirmfoto 2024-04-03 um 21 33 36" src="https://github.com/twentyhq/twenty/assets/28562999/881c2366-6274-4df7-b129-6b40a49ef214">

**Comment by Flexusma** [comment] 2024-04-03 20:13
I just wanted to open an issue for this :D. Experiencing the same thing

**Comment by charlesBochet** [comment] 2024-04-04 10:34
Hi @Flexusma @gabriel-morais 
How is this happening? Any thing special you are doing so I can reproduce?

**Comment by Flexusma** [comment] 2024-04-04 14:46
This happened to me after adding custom fields to the opportunities model (2x rating type) and then trying to add these to the default kanban view. After deleting the view and recreating it by myself it seems to work fine. Looking at the xhr/console logs it seems like an issue with multiple eventhanders firing; At times I saw 2-3x identical graphql requests.

Hope this helps :)

**Comment by Flexusma** [comment] 2024-04-04 14:59
I take it back. I just had the kanban view open for a couple minutes and added a company tab and the api got absolutely spammed 
<img width="1811" alt="grafik" src="https://github.com/twentyhq/twenty/assets/38422530/cf27725e-6b8c-4fdb-a764-27b41b08b7f8">

**Comment by Flexusma** [comment] 2024-04-04 16:49
I'm not saure it has to do with the data-model. I didn't make any changes to the data-model in the session the screenshots are from. I just had it sitting for a while after logging in, then proceeded to remove/add a field to the kanban view.

**Comment by charlesBochet** [comment] 2024-04-04 17:13
I cannot reproduce
Are you self hosting? If yes on what branch are you?

**Comment by Flexusma** [comment] 2024-04-04 17:15
I am indeed selfhosting. Latest docker image (sha256:80a9fa70925f82060e3cd80e994d99a7f2bd66f163dea9595b255c706be14aa9)

**Comment by charlesBochet** [comment] 2024-04-05 08:30
Weird, I cannot reproduce on the latest version of main. Let's wait for the 0.4.0 to be out and retry with this one

**Comment by FelixMalfait** [comment] 2024-05-17 07:40
I spent some time trying to reproduce this following you instructions @Flexusma but couldn't. I guess this has been solved so I will be closing the issue. Please re-open if you ever see this on a fresh install 🤨. Thanks to both of you for the report!

**Closed by FelixMalfait** 2024-05-17 07:40 UTC
Labels: type: bug
