### ISSUE TITLE
Issues with the placement for the app tooltip 

### ISSUE THREAD

**Issue by nimraahmed** [twentyhq/twenty#2799] opened 2023-12-03 15:55 UTC
## Bug Description

For the app tool tip, you have multiple placement options: bottom, left, right, top, top-start, top-end, right-start, right-end, bottom-start, bottom-end, left-start, and left-end

However, not all of them work as they should:

1. For both the right and left positions, the tooltip opens up on the right:

position=left:

![image](https://github.com/twentyhq/twenty/assets/50912134/e95d1e16-ae99-4529-b99d-784b5a4683c0)

position=right:

![image](https://github.com/twentyhq/twenty/assets/50912134/e7ae1c4a-bcd5-4823-90e6-d2435b58682e)

2. When position is set to top, the tooltip opens at the bottom again:

![image](https://github.com/twentyhq/twenty/assets/50912134/07162abf-e078-4f79-9a2f-895e51f9bede)

but it should open up at the top, like this:

![image](https://github.com/twentyhq/twenty/assets/50912134/6bd195ba-3fcc-4963-bd7d-4256d3abac8d)

Similarly, the following placements don't work as expected (in addition to top and left):

- top-start
- bottom-start
- bottom-end
- left-start ((opens up on the right))
- left-end (opens up on the right)

The placements that work fine are:
- bottom
- right
- right-start
- right-end

**Comment by Kanav-Arora** [comment] 2023-12-09 12:53
Hi @charlesBochet 
Can I work on this?

**Comment by charlesBochet** [comment] 2023-12-09 15:51
@Kanav-Arora sure! I'm surprised about this behavior. I wonder if this is when the tooltip doesn't have the room to go on top on the element container

**Comment by Kanav-Arora** [comment] 2023-12-09 15:56
It might be the case with the empty room so the property is applied in order of precedence. But I can give it a look if some other property is overriding it.

**Comment by FelixMalfait** [comment] 2024-01-07 16:41
@Kanav-Arora did you try and do you know if this is the expected behavior (i.e. as Charles suggested it's just because there isn't enough room), or if there is something to fix? Thanks 🙏

**Comment by Kanav-Arora** [comment] 2024-01-07 16:48
Hi @FelixMalfait 
I gave it a look I don't think so there's an issue its just due to order of precedence of property.

**Comment by FelixMalfait** [comment] 2024-01-07 21:56
Thanks @Kanav-Arora! Closing then

**Closed by FelixMalfait** 2024-01-07 21:56 UTC
Labels: type: bug, good first issue
