### ISSUE TITLE
When user tries to log in to workspace after token expiration, multiple errors appear

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6731] opened 2024-08-24 15:51 UTC
I'm not sure if scenario is reproducible as I didn't try to repeat it but here's what I did:
1. Log in
2. In Settings > Developers generate new key (save it for later)
3. In Settings > Developers add webhook URL 
4. Using Twenty docs, create simple bash script for creating 1 million companies effectively spamming REST API (or use attached script but change file format to .sh and replace key) and run it for few minutes till 1000 companies are created
5. Wait for token expiration (~30 min)
6. Try to log in

**Actual:** When user tries to log in to workspace with more than 1000 companies after token expiration, multiple errors appear
[Screencast from 2024-08-24 17-41-14.webm](https://github.com/user-attachments/assets/48257ff2-b00e-4f33-95d1-6d7bdf9b1f5b)

**Expected:** When user tries to log in to workspace with more than 1000 companies after token expiration, user should be able to log in without any problems

**Note:** While on video there's clearly visible that Companies are deactivated, I don't think they're a necessary step to reproduce bug.

Script: [1companies.txt](https://github.com/user-attachments/files/16737219/1companies.txt)

**Comment by Bonapara** [comment] 2024-08-28 15:41
@BOHEUS Can you reproduce it to help determine the root cause of this issue? Otherwise, I think I'll close it and keep the bug in mind since it's not really actionable. Thanks for pushing Twenty!

**Comment by BOHEUS** [comment] 2024-08-28 16:00
Sure, I'll report when token will expire

**Comment by BOHEUS** [comment] 2024-08-28 18:47
I was able to reproduce it on newest version of repo (mistakenly also reported it in #6732), I can't really pinpoint it in the code but it's definitely something with Apollo and useManyFindRecords like shown in the video

**Comment by charlesBochet** [comment] 2024-08-29 08:47
@BOHEUS I can reproduce, I'm working on the sign-in / token expirations issues, will ping you back!

**Comment by charlesBochet** [comment] 2024-09-01 12:24
I have made the fix but haven't tried this case yet. Any chance you could retry on the 0.24?

**Comment by BOHEUS** [comment] 2024-09-01 12:52
@charlesBochet I'll check once I have some time

**Comment by BOHEUS** [comment] 2024-09-01 16:07
@charlesBochet I can still reproduce it

**Comment by charlesBochet** [comment] 2024-09-14 15:09
Ok so it's still there! Let's see if someone from the community can fix it. If not, we will take it under 0.31 release

**Comment by FelixMalfait** [comment] 2024-11-12 14:14
@ad-elias will look into this

**Comment by FelixMalfait** [comment] 2024-11-15 16:46
Maybe look around here? Is currentWorkspaceMember null? What happens onError?
<img width="501" alt="Screenshot 2024-11-15 at 17 45 35" src="https://github.com/user-attachments/assets/b31b6157-a99f-4af5-a908-363d50c83e86">

**Closed** 2024-11-29 11:11 UTC
Labels: good first issue, scope: front, size: short, prio: high
