### ISSUE TITLE
Email Address Characters Displayed as Individual Clickable Email Links in Timeline

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#8264] opened 2024-10-31 17:54 UTC
## Bug Description

When entering a new email address, the timeline section displays each character of the email address as an individual clickable link. For instance, an email like ```ashley@qonto.com``` appears with each character as its own email button, so clicking on ```a``` prompts an email composition to "a", clicking ```s```prompts an email to "s", and so on. This behavior misinterprets the email address as separate parts rather than a single entity.

![Screenshot from 2024-10-31 23-22-08](https://github.com/user-attachments/assets/e96bd251-6a0c-42ba-b6a8-f72d962131bc)

 
[Screencast from 2024-10-31 23-06-29.webm](https://github.com/user-attachments/assets/c0635378-5030-4f34-bbce-bbc49825154b)

## Expected Behaviour
The entire email address should be a single clickable link.

![Screenshot from 2024-10-31 23-09-02](https://github.com/user-attachments/assets/42640d5e-188c-4135-8515-44a51a6c00da)

**Comment by harshit078** [comment] 2024-11-01 07:49
This behaviour is caused by how `additionalEmails` are treated in the codebase. Making sure it is treated as an array can solve this issue

**Comment by harshrajeevsingh** [comment] 2024-11-01 08:41
@harshit078 Yes, If you see the last screenshot, I parsed the ```additionalEmail``` and it worked. But I'm not sure if this is the correct solution. Because if you console log ```fieldValues```, first you will see the correct additionalEmails but then it somehow changes to a stringified version. 
I'm still looking into this.

**Comment by Bonapara** [comment] 2024-11-01 13:56
I think we had another issue for this but can't find it

**Comment by harshrajeevsingh** [comment] 2024-11-03 14:37
@Bonapara maybe this #7262

**Comment by harshrajeevsingh** [comment] 2024-11-22 05:08
@martmull This can be closed now

**Comment by charlesBochet** [comment] 2024-11-26 16:10
Fixed in 0.33.3

**Closed by charlesBochet** 2024-11-26 16:10 UTC
Labels: prio: high
