### ISSUE TITLE
Kanban views on any object feature broken

### ISSUE THREAD

**Issue by arnavsaxena17** [twentyhq/twenty#4733] opened 2024-04-01 16:48 UTC
## Bug Description
Unable to select the kanban field when trying to create a new view. The item is not selected when clicked. This was working until the last set of merges broke this feature. 

Video to demonstrate:
https://github.com/twentyhq/twenty/assets/16238974/f4764b81-1ac0-4d13-ac78-1b9023e52357

## Expected behavior
Kanban should work

**Comment by arnavsaxena17** [comment] 2024-04-02 09:36
The issue arises inspite of having a select field in the table

https://github.com/twentyhq/twenty/assets/16238974/e8d6097d-4734-404d-a55c-c9994719d60c

**Comment by martmull** [comment] 2024-04-15 10:40
@arnavsaxena17 closing because this looks fixed now, I can't reproduce the issue

**Closed by martmull** 2024-04-15 10:40 UTC
Labels: type: bug
