### ISSUE TITLE
full name input overflows out of the container

### ISSUE THREAD

**Issue by harshrajeevsingh** [twentyhq/twenty#7456] opened 2024-10-06 11:25 UTC
## Bug Description

Go to the people tab, click on a person's profile, and then click on their name to change it. The input overflows the container, which can be seen on both desktop and mobile screens. 

**Example:** 
![Screenshot from 2024-10-06 16-34-06](https://github.com/user-attachments/assets/7bef3df0-7d35-4c9b-98e2-8c55b5d7be1a)
![Screenshot from 2024-10-06 16-42-23](https://github.com/user-attachments/assets/63dcaf7a-f843-46a6-9c87-432e13620c91)

The above image shows that the first name input is clipped out of the viewport when the sidebar is collapsed. 

On Mobile screen: 
![Screenshot from 2024-10-06 16-35-29](https://github.com/user-attachments/assets/20d05a7a-30d9-4179-b6e0-4d38c2f84441)

**Comment by Bonapara** [comment] 2024-10-07 08:56
Can't reproduce 🤔 Any precision on how it occurs?

![CleanShot 2024-10-07 at 10 54 13](https://github.com/user-attachments/assets/1ba69fd2-13a4-449e-9f39-be2b52b67a3c)

**Comment by SaiAryan1784** [comment] 2024-10-08 09:11
Hi @Bonapara can i work on this issue?

**Comment by Bonapara** [comment] 2024-10-08 13:48
Can you reproduce @SaiAryan1784?

**Comment by SaiAryan1784** [comment] 2024-10-08 23:24
> Can you reproduce @SaiAryan1784?

I can try 
shall I?

**Comment by Bonapara** [comment] 2024-10-09 07:19
@SaiAryan1784 Sure, thanks. Please try to reproduce it first, as I still cannot.

**Comment by akshayjoshi892** [comment] 2024-10-15 16:59
@Bonapara 
This issue is not reproducible.

**Comment by Bonapara** [comment] 2024-10-16 09:13
closing this issue for now - please comment if you encounter the bug

**Closed by Bonapara** 2024-10-16 09:13 UTC
Labels: type: bug, good first issue, scope: front, size: short, prio: med
