### ISSUE TITLE
The timeline activity splits the additional emails into individual characters.

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#7219] opened 2024-09-23 15:01 UTC
## Bug Description

After adding an additional email to a person, the timeline activity splits the field into individual characters.

<img width="529" alt="Capture d’écran 2024-09-23 à 16 57 30" src="https://github.com/user-attachments/assets/4e2ed446-d5d8-4b71-af58-a3685c939ace">

## Expected behavior

Should display the list of additional emails correctly.

**Comment by Bonapara** [comment] 2024-09-23 15:56
Closing as duplicate of https://github.com/twentyhq/twenty/issues/7197

**Closed by Bonapara** 2024-09-23 15:56 UTC
Labels: type: bug
