### ISSUE TITLE
Disappearing header in Settings

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#7845] opened 2024-10-19 10:06 UTC
Found while testing with Playwright codegen

**Scenario:**
1. Log in
2. Go to Settings
3. Toggle "Advanced" on
4. Go to API & Webhooks
5. Create new API key or use existing one
6. Check details of API key
7. Click on API key's name input, then outside it

**Actual:** API key's name in header moved up, eventually disappearing as a result
[Screencast From 2024-10-19 12-03-21.webm](https://github.com/user-attachments/assets/f4133759-7747-4b05-b6ef-15d07b0a4516)

**Expected:** API key's name in header must stay at the same place

**Note:** Same applies to ~~webhook~~ all other tabs in Settings, triggers may be slightly different but result is the same

**Comment by Bonapara** [comment] 2024-10-19 14:44
https://github.com/user-attachments/assets/17ab0c20-45c9-4a6b-a218-e1dbeb1058b0

Cannot reproduce on main 🤔

**Comment by BOHEUS** [comment] 2024-10-19 14:48
Maybe it's only reproducible when using Playwright codegen? If so, that'd be very weird, I'll try to investigate this a bit more and find a way to reproduce it

**Comment by BOHEUS** [comment] 2024-10-19 16:08
I tried but couldn't reproduce it on main without Playwright codegen, probably it's something related to focus in Playwright codegen as it behaves differently than in normal browser?

**Comment by Bonapara** [comment] 2024-10-21 08:23
You must be right @BOHEUS. But let's close it if we can't reproduce it on end users' devices.

**Closed by Bonapara** 2024-10-21 08:23 UTC
Labels: type: bug
