### ISSUE TITLE
Link field chips hover & target blank

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5655] opened 2024-05-29 15:10 UTC
# Current Behavior

1. When hovering over a link field with several link chips, the field changes to its hover state, which is correct, but there is no effect when hovering over the chips.

https://github.com/twentyhq/twenty/assets/19412894/62548631-7612-4a5b-afd9-5cc4e27378af

2. Clicking between two chips opens a new tab with the second chip URL.

https://github.com/twentyhq/twenty/assets/19412894/d77142f7-6070-4ba5-90a6-c0a9489a1f9b

# Desired Behavior

1. Link chips should have an individual hover effect to indicate redirection when clicked.
2. External links should only open when clicking on a specific chip, not between two chips.
3. The chip design - Background color & border color - should match the Figma  (See #5938) 

# Figma

[Link Chip Figma](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=436-26817&t=P12gjv5ZcZ9hChR8-11)

![image](https://github.com/twentyhq/twenty/assets/19412894/ddbd410f-c368-4357-849b-57d01abfbd95)

[Link field Figma](https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=14603-76540&t=P12gjv5ZcZ9hChR8-11)

![image](https://github.com/twentyhq/twenty/assets/19412894/14f78c57-8cc5-4ad6-a3f0-ce476a215356)

**Comment by marteenaf** [comment] 2024-06-04 09:24
Hello @Bonapara! First time contributor here, can I be assigned to this issue?

**Comment by Bonapara** [comment] 2024-06-04 09:44
Hi @marteenaf, I think this one might be a bit too hard to tackle as a first-time contributor, maybe you can grab another one? (Unless you have a good react experience!)

**Comment by marteenaf** [comment] 2024-06-04 12:34
Ok no problem! I will have a look ar some of the other issues, thanks!

**Comment by shashankvish0010** [comment] 2024-06-04 18:13
Hi @Bonapara, I tried to reproduce the issue, but apart from the missing hover effect, I was unable to reproduce the issue with the irrelevant redirection that occurs when we click in between two `Link Chips`. Does the issue still exist?

https://github.com/twentyhq/twenty/assets/140178357/aa9c1d5b-04de-4cfd-9831-57608a644642

**Comment by Bonapara** [comment] 2024-06-05 12:19
Hi @shashankvish0010, thanks for taking a look! Yes, the issue still exists. Did you try clicking in different places? It didn't trigger everywhere for me either.

**Closed** 2024-08-30 13:12 UTC
Labels: scope: front, size: hours, good for experienced contributor
