### ISSUE TITLE
v.0.30.2 - Deleting company twice will soft delete all of the workspace’s companies

### ISSUE THREAD

**Issue by raphspeaks** [twentyhq/twenty#7482] opened 2024-10-07 21:10 UTC
## Bug Description

When using the soft delete functionality the UI will soft delete all of the workspace companies. 

**To Recreate:** 

Log into your v.0.30.2 workspace and soft delete a company. Then proceed to the “Deleted Companies” UI section. Use the “Select All” action to select the company that you just deleted and delete it again. This results in the UI soft deleting all of the workspace’s companies.

## Expected behavior

An initial delete action should result in a soft deleted item. A delete action from the “Deleted Companies” UI should result in a permanently deleted record.  

## Technical inputs

None for now.

**Comment by raphspeaks** [comment] 2024-10-07 21:14
For those of you who experienced this problem. I was able to restore the soft delete with the following:

```update workspace_{workspaceid}.company set "deletedAt" = null;```

Thanks @BOHEUS for the support. 

***Make sure you back up your data first!***

**Comment by Bonapara** [comment] 2024-10-08 16:12
I couldn't reproduce the issue. If someone wants to investigate, please do!

**Comment by raphspeaks** [comment] 2024-10-09 16:35
I updated the issue to be more specific about using the “Select All” action.

**Comment by Bonapara** [comment] 2024-10-10 08:15
Can reproduce, thanks for the clarifications @raphspeaks!

**Comment by Bonapara** [comment] 2024-10-10 08:17
@charlesBochet FYI

**Comment by charlesBochet** [comment] 2024-10-13 08:48
This issue has been fixed in 0.31.1 :)

**Closed by charlesBochet** 2024-10-13 08:48 UTC
Labels: type: bug, scope: front, prio: high
