### ISSUE TITLE
Add object's id and foreign key to csv exports

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5893] opened 2024-06-17 08:19 UTC
Having the object id and relationships will be very helpful for upsert use-cases when the user exports the data, then transforms it in a spreadsheet, then re-import it

**Comment by AdityaPimpalkar** [comment] 2024-06-17 08:46
Hey, I can take this up 👍

**Comment by raphaelm-gioa** [comment] 2024-06-20 09:39
Is this a duplicate of https://github.com/twentyhq/twenty/issues/5485 then ?

**Closed** 2024-06-20 14:42 UTC

**Comment by FelixMalfait** [comment] 2024-06-20 16:13
@raphaelm-gioa this one is about adding Ids to **export**, the other one is about **import**ing relationships :)
