### ISSUE TITLE
Creating empty objects

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6633] opened 2024-08-15 19:26 UTC
**Scenario:**
1. Log in
2. Go to Companies
3. Create new object by either pressing '+' in right top corner or 'c' on keyboard, type anything, delete it and press Enter

**Actual:** Object is created
![image](https://github.com/user-attachments/assets/6fe2c6bd-581c-4bbd-a0a3-4d5739cb92c4)

**Expected:** Object shouldn't be created due to missing data like name

**Comment by ShadabImran07** [comment] 2024-08-17 18:12
i wanna work on this issue please assigned to me

**Comment by ShadabImran07** [comment] 2024-08-17 19:29
I would like to report the same issue, but it is happening across all companies, people, and opportunities,task,notes. For reference, I have added a screenshot of the issue.
![Screenshot 2024-08-18 005720](https://github.com/user-attachments/assets/2fb22332-b4f6-4c02-b50f-ca5cf426645a)
![Screenshot 2024-08-18 005741](https://github.com/user-attachments/assets/f85d6ce3-8afb-4fe3-a3c8-04bc0c983a24)
![Screenshot 2024-08-18 005806](https://github.com/user-attachments/assets/3eca8fcf-48f1-455d-8fcd-f3d10f12477d)
![Screenshot 2024-08-18 005822](https://github.com/user-attachments/assets/7602285e-6e71-4f03-a70c-f759d151121e)

**Comment by BOHEUS** [comment] 2024-08-17 19:33
I can't assign it as I don't have enough permissions and yes, this issue is across all objects, both standard and custom, should have explain it better earlier.

**Comment by Nabhag8848** [comment] 2024-08-25 11:04
Hey @BOHEUS Can't reproduce, Am I missing anything, attaching video, `pressed **Enter** without any other interaction`. 

https://github.com/user-attachments/assets/c023eb3e-704f-498e-8a74-7fc95daa3a63

.

**Comment by BOHEUS** [comment] 2024-08-25 11:24
Just to prove my point, I'm reproducing it on demo (and I'm not sure but @ehconitin may be working on it together with #6630)
[Screencast from 2024-08-25 13-19-42.webm](https://github.com/user-attachments/assets/f205b8c4-a355-4a3c-99ee-429ad3c39fe9)

**Comment by harshit078** [comment] 2024-08-25 12:35
One potential approach to this issue can be that if we use `trim()` functionality to check for whitespaces and` throw new Error` and implement this functionality in handleEnter, handleTab, handleClickOutside and etc. As a result empty cell would not be created. What are your views on this ? @BOHEUS @Nabhag8848

**Comment by BOHEUS** [comment] 2024-08-25 12:38
I'll leave the decision to @CoreTeamTwenty

**Comment by Nabhag8848** [comment] 2024-08-25 12:44
Working on it, as I think I'm very close and already figured out the cause, I think probably on the last keystroke, when deleting the string. there is state mismatch, cause this doesn't happen for example when we don't change /  write anything in Name Field and Press **Enter**.

> One potential approach to this issue can be that if we use `trim()` functionality to check for whitespaces and` throw new Error` and implement this functionality in `handleEnter`, `handleTab`,` handleClickOutside` and etc. As a result empty cell would not be created. What are your views on this ? @BOHEUS @Nabhag8848

**Closed** 2024-09-20 19:25 UTC
Labels: type: bug
