### ISSUE TITLE
[Firefox] Dropdowns have too big transparency

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#6777] opened 2024-08-28 18:55 UTC
**Scenario:**
1. Log in using Firefox or Librewolf
2. Go to Settings > Appearance
3. Select dark mode (optional but it can be also reproduced in dark mode)
4. Click on any dropdown

**Actual:** Dropdowns have too big transparency
![image](https://github.com/user-attachments/assets/e1f1e37e-48d6-4e03-9f87-c371fff681d1)
![image](https://github.com/user-attachments/assets/0883eae6-3502-4db6-a301-1fbc7b09f59d)

**Expected:** Dropdowns should have no transparency

**Note:** Also found one in Settings > Developers > Webhook details
![image](https://github.com/user-attachments/assets/4446eada-c5a4-44f7-854a-eb2cc6b04ae9)

**Comment by Bonapara** [comment] 2024-08-29 09:09
![CleanShot 2024-08-29 at 11 09 01](https://github.com/user-attachments/assets/7068d25a-44c8-46cf-93e1-853e862bea9a)

Working fine for me, do you experience this issue somewhere else in the app @BOHEUS?

**Comment by BOHEUS** [comment] 2024-08-29 18:10
@Bonapara I think it's more of a browser problem as I can't reproduce it on Chromium-based browsers like Chrome or Brave but it's only on Firefox, I'm changing the title to highlight the problem with specific browser

**Comment by charlesBochet** [comment] 2024-09-01 11:38
Good catch! We are using background-blur + opacity to compute the opacity. We should double check how background-blur looks like on Firefox.

Note that on chrome we cannot have a container with background-blur having a child with background-blur itself (in this case the background blur is not applied at all), I don't know if this is also the case in Firefox. But that's why sometimes we choose to Portal the component or to add isBackgroundBlurEnabled on some components to avoid the issue.
(However, I don't think this is related)

**Comment by Bonapara** [comment] 2024-10-01 20:02
/oss.gg 150

**Comment by nganphan123** [comment] 2024-10-02 07:34
Hi @Bonapara , I'd love to work on this. Could you assign it to me? Thank you!

**Comment by Bonapara** [comment] 2024-10-02 07:53
@nganphan123, do you want to handle this issue into the OSS.GG hackathon context? If so, please sign up on OSS.GG and comment /assign, otherwise happy to assign it to you manually!

**Comment by PratikAwaik** [comment] 2024-10-04 00:28
@Bonapara Looks like this issue is fixed? I don't see this issue happening on firefox.

**Comment by Bonapara** [comment] 2024-10-04 07:47
![CleanShot 2024-10-04 at 09 46 39](https://github.com/user-attachments/assets/bdd82e7c-beef-4aec-9bda-5af0eb74f8ce)

Closing as can't reproduce either on Firefox

**Closed by Bonapara** 2024-10-04 07:47 UTC
Labels: type: bug, good first issue, scope: front, size: short, prio: low, 🕹️ oss.gg, :joystick: 150 points
