### ISSUE TITLE
v0.32.0 - Failed to execute 'removeChild' when applying filters

### ISSUE THREAD

**Issue by dkdps** [twentyhq/twenty#8602] opened 2024-11-20 10:48 UTC
## Bug Description

When I try to apply a filter on the **opportunities** tab, I get this error. Seems to only happen on columns with the **select** data type. (See screenshots)

I might investigate later if I get time. It would be helpful to gauge if anyone else has experienced the same.

![Image](https://github.com/user-attachments/assets/ae5c3999-c814-40a6-903c-dd2b1d0d6d92)
![Image](https://github.com/user-attachments/assets/0ff2a1b6-6f6a-48f1-865b-73f2ac590838)
![Image](https://github.com/user-attachments/assets/dc8e6e12-334a-41ea-a374-624d1b393329)
![Image](https://github.com/user-attachments/assets/82674afb-c98f-435c-96a5-d0ed5375fc33)

## Expected behavior

Filters on select data types are applied.

## Technical inputs

- Seems to be a frontend bug: backend doesn't display any errors and my browser console does log an error. (See screenshot)
- This is running on v0.32.0 with the [1 step docker deployment](https://twenty.com/developers/section/self-hosting/docker-compose)

**Comment by charlesBochet** [comment] 2024-11-20 14:30
Thanks for creating an issue, tagging this one as urgent bug and we will try to take it on 0.33 version for end of the week

**Comment by ehconitin** [comment] 2024-11-20 20:42
@dkdps could you share more details? I can apply filters on stages in the opportunity tab's column with no errors.
A screen recording on how to reproduce this behavior would be helpful! Thanks

**Comment by ehconitin** [comment] 2024-11-21 07:34
@dkdps Thanks! This bug does exist on v0.32.0. @charlesBochet I suspect this was related to the scroll wrapper bug where it couldn't take multiple children which we fixed by wrapping children in a div https://github.com/twentyhq/twenty/pull/8570. I couldn't reproduce it on the main.

**Comment by martmull** [comment] 2024-11-22 10:32
can't reproduce what did I missed?
https://github.com/user-attachments/assets/4e8b7694-8724-4436-922d-12fee7407d6d

**Comment by ehconitin** [comment] 2024-11-22 10:33
Are you checking on main? @martmull

**Comment by martmull** [comment] 2024-11-22 10:36
yep

**Comment by ehconitin** [comment] 2024-11-22 10:37
Its fixed :) was waiting on charles to confirm before closing this!

**Comment by ehconitin** [comment] 2024-11-22 10:40
The bug is on 0.32.0 tagged release, I confirmed.

**Closed** 2024-11-22 13:30 UTC
Labels: prio: high
