### ISSUE TITLE
Update the People & Companies Options menu

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1510] opened 2023-09-07 22:58 UTC
# Current behavior 

Wrongly implemented by #1147 

# Desired behavior:

When I click on "add view" in the view switcher menu, it creates a new view and opens the option menu with the name input on focus. This is how a user will be able to customize the new view name and edit it later. In the following video, I first click on "Option" to show it's the same option menu that opens when you click on "add view" (it's not part of the flow)

Figma: 
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=8995-27160&mode=design&t=SemXydYipC9nY5Lx-4

https://github.com/twentyhq/twenty/assets/19412894/79353ccc-5541-4628-ac75-84e267d4cedc

**V1** can skip the icon switcher at the left of the input, and make the input take the full width:

![Image](https://github.com/twentyhq/twenty/assets/19412894/88c1bdea-7ae7-44c3-b7b0-53c33e2f4a5e)

**Comment by charlesBochet** [comment] 2023-09-18 06:00
Let's introduce new items in the DropdownMenu:
- DropdownMenuSearchInput (which should be the existing DropdownMenuInput)
- DropdownMenuInput which should implement this new design

**Comment by charlesBochet** [comment] 2023-09-18 06:48
Looks duplicate of https://github.com/twentyhq/twenty/issues/1253

**Comment by charlesBochet** [comment] 2023-09-19 16:08
Only refactor into a separate component and add tests

**Comment by charlesBochet** [comment] 2023-09-19 16:09
Also add it to Board

**Closed** 2023-09-20 19:53 UTC
