### ISSUE TITLE
Custom fields lacks empty tag

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7250] opened 2024-09-25 11:24 UTC
## Bug Description

- Custom fields lacks empty tag as a result they have very limited clickable area to edit them.
- This creates a lot of whitespaces in front of fields which hinders the design

## Current behavior
<img width="348" alt="Screenshot 2024-09-25 at 4 35 00 PM" src="https://github.com/user-attachments/assets/62ca4c6b-8d7f-4300-a734-8f13334c8e55">

<img width="332" alt="Screenshot 2024-09-25 at 4 54 13 PM" src="https://github.com/user-attachments/assets/b03ff92e-84ae-41e2-b04a-896d1af31160">

## Expected

There should be empty tags in front of custom fields when empty

**Comment by Bonapara** [comment] 2024-09-25 12:01
I cannot reproduce the bug 🤔 Any idea/ more context?

![CleanShot 2024-09-25 at 14 00 31](https://github.com/user-attachments/assets/50254c6c-766d-478c-a625-cc807ad9bc3b)

**Comment by FelixMalfait** [comment] 2024-10-14 19:43
/oss.gg 200

**Comment by nganphan123** [comment] 2024-10-16 01:08
Hi, is this available to be taken? Can I work on this?

**Comment by nganphan123** [comment] 2024-10-16 03:52
Hi @Bonapara , I did some inspection and it seems like the Empty tag is missing for Multi-select and One-to-many data type. The problem lies in the check `isDisplayModeContentEmpty` for empty content, which is referring to function `isFieldValueEmpty()`
https://github.com/twentyhq/twenty/blob/1b99a05dec535167b68b062e1680f3dc7eebaa2b/packages/twenty-front/src/modules/object-record/record-inline-cell/components/RecordInlineCellDisplayMode.tsx#L89-L94

From what I understand, the `isFieldValueEmpty()` doesn't properly check if the array is empty. My solution would be adding changes to `isFieldValueEmpty()` to check the empty array for fields multi-select and relation. 

Please let me know if I'm on the right track or if there's anything I've misunderstood. Thank you!

**Comment by Bonapara** [comment] 2024-10-16 09:11
@lucasbordeau WDYT?

**Comment by FelixMalfait** [comment] 2024-10-16 15:49
@nganphan123 yes it seems you're on the right track! Thank you!

**Comment by nganphan123** [comment] 2024-10-17 07:45
Hi @Bonapara @FelixMalfait , I have a quick question. I'm testing out and adding the check for empty array of relation data type in `isFieldValueEmpty()` . However, there are 2 types `FieldRelationToOne` and `FieldRelationToMany`. It seems that only the relation to many has the array type. Shall I split the check for them or combine them into one check like below? I also created a draft PR to better explain what I mean #7777
```typescript  
if (isFieldRelation(fieldDefinition)) {
    return (
      !isFieldRelationToOneValue(fieldValue) ||
      !isFieldRelationFromManyValue(fieldValue) ||
      !isNonEmptyArray(fieldValue)
    );
}
```

**Comment by FelixMalfait** [comment] 2024-10-17 07:56
@nganphan123 fyi we never really shiped relationToOne in the product in the end.  

I'd probably do something like this instead (not tested):

```
if (isFieldRelation(fieldDefinition)) {
   if(isFieldRelationToOneValue(fieldValue)) {
       return isValueEmpty(fieldValue);
   }
    return  !isNonEmptyArray(fieldValue);
}
```
Close to what you're saying but better handling of RelationToOne imo (even though we don't use it)

**Comment by nganphan123** [comment] 2024-10-17 08:54
@FelixMalfait  I see. I added the change and it passed the tests. Also,  `isFieldRelationToOneValue` and `isFieldRelationFromManyValue` have the same implementation so it didn't identify which field is RelationToMany, so I changed to `isArray` instead.
```
  if (isFieldRelation(fieldDefinition)) {
    if (isArray(fieldValue)) {
      return !isNonEmptyArray(fieldValue);
    }
    return isValueEmpty(fieldValue);
  }
```

**Comment by BOHEUS** [comment] 2024-11-02 18:57
@FelixMalfait this issue can be closed since changes are merged

**Comment by FelixMalfait** [comment] 2024-11-03 15:33
Thanks @BOHEUS

**Closed by FelixMalfait** 2024-11-03 15:33 UTC
Labels: type: bug, good first issue, scope: front
