### ISSUE TITLE
Menus "go back" button style fix

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#1582] opened 2023-09-14 21:46 UTC
# Current behavior

The Hover and "go back" behavior is carried by the full menu item. 

https://github.com/twentyhq/twenty/assets/19412894/67341954-fdcf-4af5-b4af-5059ae736b2c

# Desired design

The hover and "go back" behavior should only be carried by the "icon button" and not on the full menu item container.

https://github.com/twentyhq/twenty/assets/19412894/0b4d4eb2-c937-4e9e-aca8-c53b0e125a82

# Figma

https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=6377-158599&mode=design&t=Bks836akwMMnwvOf-4

**Comment by Amandixit10** [comment] 2023-09-18 06:36
Hi @Bonapara, can you please assign this issue to me. Thanks.

**Comment by Bonapara** [comment] 2023-09-19 22:39
Done, @Amandixit10. Thanks a lot!

**Comment by RayG-XD** [comment] 2023-09-28 16:11
Hi @Bonapara ,

I'm interested in contributing to the project. I noticed the issue is already assigned. If the current assignee encounters any difficulties, I'm happy to assist.

Thank you for your consideration.

**Comment by Bonapara** [comment] 2023-09-29 12:12
@Amandixit10 are you still on it? Otherwise @RayG-XD I can assign you! Please mention me in your answer

**Comment by Amandixit10** [comment] 2023-09-29 14:20
> @Amandixit10 are you still on it? Otherwise @RayG-XD I can assign you! Please mention me in your answer

You can assign him, i am currently into something. Sorry for the inconvenience caused.

**Comment by Bonapara** [comment] 2023-10-02 07:49
No pb @Amandixit10
@RayG-XD, Still interested?

Thank you both!

**Comment by alfredlouisw8** [comment] 2023-10-03 10:21
hi @Bonapara 
can you assign this to me if no one is working on this?

Thankyou!

**Closed** 2023-10-05 13:30 UTC
Labels: good first issue, scope: front, ready, size: minutes, type: design improvement
