### ISSUE TITLE
Soft deleted records can't be permamently deleted

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8101] opened 2024-10-26 19:14 UTC
**Scenario:**
1. Log in
2. Go to People tab (or any other tab)
3. Select and delete any record
4. Open Deleted People view
5. Try to delete soft deleted record

**Actual:** Soft deleted records can't be permamently deleted and number of records is wrong
[Screencast From 2024-10-26 21-13-32.webm](https://github.com/user-attachments/assets/91d7edf8-8bbd-4d32-a998-1b216f8b5b13)

**Expected:** Soft deleted records can be permamently deleted and number of records is correct

CC: @Weiko

**Comment by Bonapara** [comment] 2024-10-28 14:14
Closing as duplicate of https://github.com/twentyhq/twenty/issues/7066

**Closed by Bonapara** 2024-10-28 14:14 UTC
Labels: type: bug
