### ISSUE TITLE
[Timebox] Move all objects from prisma to typeorm

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#2368] opened 2023-11-06 12:56 UTC
## Scope & Context

We already have a few PRs opened from the community, we need to take the time to merge them and handle the new RELATION type.

Part of it is in this issue as well https://github.com/twentyhq/twenty/issues/2109

## Technical inputs

[Timebox]

**Comment by magrinj** [comment] 2023-11-06 13:13
It's a duplicate of #1824

**Comment by charlesBochet** [comment] 2023-11-14 13:04
Closing this issue as duplicated

**Closed by charlesBochet** 2023-11-14 13:04 UTC
Labels: scope: backend, type: chore
